#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_Downloademailasattachment")]
	public partial class @__DownloademailasattachmentRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string emailIdToBeDownloaded = "emailIdToBeDownloaded";
			public const string additionalParameter = "additionalParameter";
		}
		
		public const string ActionLogicalName = "_Downloademailasattachment";
		
		public string emailIdToBeDownloaded
		{
			get
			{
				if (this.Parameters.Contains("emailIdToBeDownloaded"))
				{
					return ((string)(this.Parameters["emailIdToBeDownloaded"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["emailIdToBeDownloaded"] = value;
			}
		}
		
		public string additionalParameter
		{
			get
			{
				if (this.Parameters.Contains("additionalParameter"))
				{
					return ((string)(this.Parameters["additionalParameter"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["additionalParameter"] = value;
			}
		}
		
		public @__DownloademailasattachmentRequest()
		{
			this.RequestName = "_Downloademailasattachment";
			this.emailIdToBeDownloaded = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_Downloademailasattachment")]
	public partial class @__DownloademailasattachmentResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string emailRecordData = "emailRecordData";
		}
		
		public const string ActionLogicalName = "_Downloademailasattachment";
		
		public @__DownloademailasattachmentResponse()
		{
		}
		
		public string emailRecordData
		{
			get
			{
				if (this.Results.Contains("emailRecordData"))
				{
					return ((string)(this.Results["emailRecordData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["emailRecordData"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
