#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_SyncKnowledgeManagementSettings")]
	public partial class @__SyncKnowledgeManagementSettingsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "_SyncKnowledgeManagementSettings";
		
		public @__SyncKnowledgeManagementSettingsRequest()
		{
			this.RequestName = "_SyncKnowledgeManagementSettings";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_SyncKnowledgeManagementSettings")]
	public partial class @__SyncKnowledgeManagementSettingsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "_SyncKnowledgeManagementSettings";
		
		public @__SyncKnowledgeManagementSettingsResponse()
		{
		}
	}
}
#pragma warning restore CS1591
