#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AddComponentToSolutionAsync")]
	public partial class AddComponentToSolutionAsyncRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string IncludeEntityMetadata = "IncludeEntityMetadata";
			public const string LogicalName = "LogicalName";
			public const string IncludeChildComponents = "IncludeChildComponents";
			public const string Id = "Id";
			public const string AddRequiredComponents = "AddRequiredComponents";
			public const string SolutionUniqueName = "SolutionUniqueName";
		}
		
		public const string ActionLogicalName = "AddComponentToSolutionAsync";
		
		public System.Nullable<bool> IncludeEntityMetadata
		{
			get
			{
				if (this.Parameters.Contains("IncludeEntityMetadata"))
				{
					return ((System.Nullable<bool>)(this.Parameters["IncludeEntityMetadata"]));
				}
				else
				{
					return default(System.Nullable<bool>);
				}
			}
			set
			{
				this.Parameters["IncludeEntityMetadata"] = value;
			}
		}
		
		public string LogicalName
		{
			get
			{
				if (this.Parameters.Contains("LogicalName"))
				{
					return ((string)(this.Parameters["LogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LogicalName"] = value;
			}
		}
		
		public System.Nullable<bool> IncludeChildComponents
		{
			get
			{
				if (this.Parameters.Contains("IncludeChildComponents"))
				{
					return ((System.Nullable<bool>)(this.Parameters["IncludeChildComponents"]));
				}
				else
				{
					return default(System.Nullable<bool>);
				}
			}
			set
			{
				this.Parameters["IncludeChildComponents"] = value;
			}
		}
		
		public System.Guid Id
		{
			get
			{
				if (this.Parameters.Contains("Id"))
				{
					return ((System.Guid)(this.Parameters["Id"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["Id"] = value;
			}
		}
		
		public bool AddRequiredComponents
		{
			get
			{
				if (this.Parameters.Contains("AddRequiredComponents"))
				{
					return ((bool)(this.Parameters["AddRequiredComponents"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["AddRequiredComponents"] = value;
			}
		}
		
		public string SolutionUniqueName
		{
			get
			{
				if (this.Parameters.Contains("SolutionUniqueName"))
				{
					return ((string)(this.Parameters["SolutionUniqueName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionUniqueName"] = value;
			}
		}
		
		public AddComponentToSolutionAsyncRequest()
		{
			this.RequestName = "AddComponentToSolutionAsync";
			this.LogicalName = default(string);
			this.Id = default(System.Guid);
			this.AddRequiredComponents = default(bool);
			this.SolutionUniqueName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AddComponentToSolutionAsync")]
	public partial class AddComponentToSolutionAsyncResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AsyncOperationId = "AsyncOperationId";
		}
		
		public const string ActionLogicalName = "AddComponentToSolutionAsync";
		
		public AddComponentToSolutionAsyncResponse()
		{
		}
		
		public System.Guid AsyncOperationId
		{
			get
			{
				if (this.Results.Contains("AsyncOperationId"))
				{
					return ((System.Guid)(this.Results["AsyncOperationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["AsyncOperationId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
