#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AddWorkQueueItemProcessingHistoryEntry")]
	public partial class AddWorkQueueItemProcessingHistoryEntryRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
			public const string Item_1 = "Item_1";
		}
		
		public const string ActionLogicalName = "AddWorkQueueItemProcessingHistoryEntry";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity Item_1
		{
			get
			{
				if (this.Parameters.Contains("item"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["item"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["item"] = value;
			}
		}
		
		public AddWorkQueueItemProcessingHistoryEntryRequest()
		{
			this.RequestName = "AddWorkQueueItemProcessingHistoryEntry";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Item_1 = default(Microsoft.Xrm.Sdk.Entity);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AddWorkQueueItemProcessingHistoryEntry")]
	public partial class AddWorkQueueItemProcessingHistoryEntryResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "AddWorkQueueItemProcessingHistoryEntry";
		
		public AddWorkQueueItemProcessingHistoryEntryResponse()
		{
		}
	}
}
#pragma warning restore CS1591
