#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AIClassify")]
	public partial class AIClassifyRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string AllowMultipleCategories = "AllowMultipleCategories";
			public const string Categories = "Categories";
			public const string Text = "Text";
		}
		
		public const string ActionLogicalName = "AIClassify";
		
		public bool AllowMultipleCategories
		{
			get
			{
				if (this.Parameters.Contains("AllowMultipleCategories"))
				{
					return ((bool)(this.Parameters["AllowMultipleCategories"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["AllowMultipleCategories"] = value;
			}
		}
		
		public string[] Categories
		{
			get
			{
				if (this.Parameters.Contains("Categories"))
				{
					return ((string[])(this.Parameters["Categories"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["Categories"] = value;
			}
		}
		
		public string Text
		{
			get
			{
				if (this.Parameters.Contains("Text"))
				{
					return ((string)(this.Parameters["Text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Text"] = value;
			}
		}
		
		public AIClassifyRequest()
		{
			this.RequestName = "AIClassify";
			this.AllowMultipleCategories = default(bool);
			this.Categories = default(string[]);
			this.Text = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AIClassify")]
	public partial class AIClassifyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Classification = "Classification";
		}
		
		public const string ActionLogicalName = "AIClassify";
		
		public AIClassifyResponse()
		{
		}
		
		public string Classification
		{
			get
			{
				if (this.Results.Contains("Classification"))
				{
					return ((string)(this.Results["Classification"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Classification"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
