#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AIModelPublish")]
	public partial class AIModelPublishRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RunConfigurationId = "RunConfigurationId";
			public const string TemplateId = "TemplateId";
			public const string CustomConfiguration = "CustomConfiguration";
			public const string ModelName = "ModelName";
			public const string ModelId = "ModelId";
			public const string Source = "Source";
			public const string RunConfiguration = "RunConfiguration";
		}
		
		public const string ActionLogicalName = "AIModelPublish";
		
		public System.Guid RunConfigurationId
		{
			get
			{
				if (this.Parameters.Contains("RunConfigurationId"))
				{
					return ((System.Guid)(this.Parameters["RunConfigurationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["RunConfigurationId"] = value;
			}
		}
		
		public System.Guid TemplateId
		{
			get
			{
				if (this.Parameters.Contains("TemplateId"))
				{
					return ((System.Guid)(this.Parameters["TemplateId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["TemplateId"] = value;
			}
		}
		
		public string CustomConfiguration
		{
			get
			{
				if (this.Parameters.Contains("CustomConfiguration"))
				{
					return ((string)(this.Parameters["CustomConfiguration"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CustomConfiguration"] = value;
			}
		}
		
		public string ModelName
		{
			get
			{
				if (this.Parameters.Contains("ModelName"))
				{
					return ((string)(this.Parameters["ModelName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ModelName"] = value;
			}
		}
		
		public System.Guid ModelId
		{
			get
			{
				if (this.Parameters.Contains("ModelId"))
				{
					return ((System.Guid)(this.Parameters["ModelId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["ModelId"] = value;
			}
		}
		
		public string Source
		{
			get
			{
				if (this.Parameters.Contains("Source"))
				{
					return ((string)(this.Parameters["Source"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Source"] = value;
			}
		}
		
		public string RunConfiguration
		{
			get
			{
				if (this.Parameters.Contains("RunConfiguration"))
				{
					return ((string)(this.Parameters["RunConfiguration"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RunConfiguration"] = value;
			}
		}
		
		public AIModelPublishRequest()
		{
			this.RequestName = "AIModelPublish";
			this.RunConfigurationId = default(System.Guid);
			this.TemplateId = default(System.Guid);
			this.CustomConfiguration = default(string);
			this.ModelName = default(string);
			this.ModelId = default(System.Guid);
			this.RunConfiguration = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AIModelPublish")]
	public partial class AIModelPublishResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ModelInfo = "ModelInfo";
		}
		
		public const string ActionLogicalName = "AIModelPublish";
		
		public AIModelPublishResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity ModelInfo
		{
			get
			{
				if (this.Results.Contains("ModelInfo"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["ModelInfo"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["ModelInfo"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
