#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AIReply")]
	public partial class AIReplyRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Text = "Text";
		}
		
		public const string ActionLogicalName = "AIReply";
		
		public string Text
		{
			get
			{
				if (this.Parameters.Contains("Text"))
				{
					return ((string)(this.Parameters["Text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Text"] = value;
			}
		}
		
		public AIReplyRequest()
		{
			this.RequestName = "AIReply";
			this.Text = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AIReply")]
	public partial class AIReplyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string PreparedResponse = "PreparedResponse";
		}
		
		public const string ActionLogicalName = "AIReply";
		
		public AIReplyResponse()
		{
		}
		
		public string PreparedResponse
		{
			get
			{
				if (this.Results.Contains("PreparedResponse"))
				{
					return ((string)(this.Results["PreparedResponse"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["PreparedResponse"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
