#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AISummarizeRecord")]
	public partial class AISummarizeRecordRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntityLogicalName = "EntityLogicalName";
			public const string Id = "Id";
			public const string RecordContext = "RecordContext";
			public const string IsMergedCatchupAndSummary = "IsMergedCatchupAndSummary";
		}
		
		public const string ActionLogicalName = "AISummarizeRecord";
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public string Id
		{
			get
			{
				if (this.Parameters.Contains("Id"))
				{
					return ((string)(this.Parameters["Id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Id"] = value;
			}
		}
		
		public string RecordContext
		{
			get
			{
				if (this.Parameters.Contains("RecordContext"))
				{
					return ((string)(this.Parameters["RecordContext"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordContext"] = value;
			}
		}
		
		public bool IsMergedCatchupAndSummary
		{
			get
			{
				if (this.Parameters.Contains("IsMergedCatchupAndSummary"))
				{
					return ((bool)(this.Parameters["IsMergedCatchupAndSummary"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsMergedCatchupAndSummary"] = value;
			}
		}
		
		public AISummarizeRecordRequest()
		{
			this.RequestName = "AISummarizeRecord";
			this.EntityLogicalName = default(string);
			this.Id = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AISummarizeRecord")]
	public partial class AISummarizeRecordResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AdditionalInformation = "AdditionalInformation";
			public const string SummarizedText = "SummarizedText";
		}
		
		public const string ActionLogicalName = "AISummarizeRecord";
		
		public AISummarizeRecordResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity AdditionalInformation
		{
			get
			{
				if (this.Results.Contains("AdditionalInformation"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["AdditionalInformation"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["AdditionalInformation"] = value;
			}
		}
		
		public string SummarizedText
		{
			get
			{
				if (this.Results.Contains("SummarizedText"))
				{
					return ((string)(this.Results["SummarizedText"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["SummarizedText"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
