#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AISummarize")]
	public partial class AISummarizeRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Text = "Text";
		}
		
		public const string ActionLogicalName = "AISummarize";
		
		public string Text
		{
			get
			{
				if (this.Parameters.Contains("Text"))
				{
					return ((string)(this.Parameters["Text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Text"] = value;
			}
		}
		
		public AISummarizeRequest()
		{
			this.RequestName = "AISummarize";
			this.Text = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AISummarize")]
	public partial class AISummarizeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string SummarizedText = "SummarizedText";
		}
		
		public const string ActionLogicalName = "AISummarize";
		
		public AISummarizeResponse()
		{
		}
		
		public string SummarizedText
		{
			get
			{
				if (this.Results.Contains("SummarizedText"))
				{
					return ((string)(this.Results["SummarizedText"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["SummarizedText"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
