#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AppendRelatedParty")]
	public partial class AppendRelatedPartyRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Activity = "Activity";
			public const string Party = "Party";
		}
		
		public const string ActionLogicalName = "AppendRelatedParty";
		
		public Microsoft.Xrm.Sdk.EntityReference Activity
		{
			get
			{
				if (this.Parameters.Contains("Activity"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Activity"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Activity"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Party
		{
			get
			{
				if (this.Parameters.Contains("Party"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Party"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Party"] = value;
			}
		}
		
		public AppendRelatedPartyRequest()
		{
			this.RequestName = "AppendRelatedParty";
			this.Activity = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Party = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AppendRelatedParty")]
	public partial class AppendRelatedPartyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "AppendRelatedParty";
		
		public AppendRelatedPartyResponse()
		{
		}
	}
}
#pragma warning restore CS1591
