#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("BeginMachineImageProvisioning")]
	public partial class BeginMachineImageProvisioningRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string vmImageName = "vmImageName";
			public const string vmImageDescription = "vmImageDescription";
			public const string sharedImageGalleryDestination = "sharedImageGalleryDestination";
			public const string machineImageSource = "machineImageSource";
		}
		
		public const string ActionLogicalName = "BeginMachineImageProvisioning";
		
		public string vmImageName
		{
			get
			{
				if (this.Parameters.Contains("vmImageName"))
				{
					return ((string)(this.Parameters["vmImageName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["vmImageName"] = value;
			}
		}
		
		public string vmImageDescription
		{
			get
			{
				if (this.Parameters.Contains("vmImageDescription"))
				{
					return ((string)(this.Parameters["vmImageDescription"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["vmImageDescription"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity sharedImageGalleryDestination
		{
			get
			{
				if (this.Parameters.Contains("sharedImageGalleryDestination"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["sharedImageGalleryDestination"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["sharedImageGalleryDestination"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity machineImageSource
		{
			get
			{
				if (this.Parameters.Contains("machineImageSource"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["machineImageSource"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["machineImageSource"] = value;
			}
		}
		
		public BeginMachineImageProvisioningRequest()
		{
			this.RequestName = "BeginMachineImageProvisioning";
			this.vmImageName = default(string);
			this.sharedImageGalleryDestination = default(Microsoft.Xrm.Sdk.Entity);
			this.machineImageSource = default(Microsoft.Xrm.Sdk.Entity);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("BeginMachineImageProvisioning")]
	public partial class BeginMachineImageProvisioningResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string flowMachineImageId = "flowMachineImageId";
			public const string flowMachineImageVersionId = "flowMachineImageVersionId";
		}
		
		public const string ActionLogicalName = "BeginMachineImageProvisioning";
		
		public BeginMachineImageProvisioningResponse()
		{
		}
		
		public System.Guid flowMachineImageId
		{
			get
			{
				if (this.Results.Contains("flowMachineImageId"))
				{
					return ((System.Guid)(this.Results["flowMachineImageId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["flowMachineImageId"] = value;
			}
		}
		
		public System.Guid flowMachineImageVersionId
		{
			get
			{
				if (this.Results.Contains("flowMachineImageVersionId"))
				{
					return ((System.Guid)(this.Results["flowMachineImageVersionId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["flowMachineImageVersionId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
