#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ConnectToGit")]
	public partial class ConnectToGitRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Organization = "Organization";
			public const string UpstreamBranch = "UpstreamBranch";
			public const string SolutionUniqueName = "SolutionUniqueName";
			public const string ConnectionType = "ConnectionType";
			public const string RootFolder = "RootFolder";
			public const string Branch = "Branch";
			public const string Project = "Project";
			public const string GitFolder = "GitFolder";
			public const string GitProvider = "GitProvider";
			public const string Repository = "Repository";
		}
		
		public const string ActionLogicalName = "ConnectToGit";
		
		public string Organization
		{
			get
			{
				if (this.Parameters.Contains("Organization"))
				{
					return ((string)(this.Parameters["Organization"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Organization"] = value;
			}
		}
		
		public string UpstreamBranch
		{
			get
			{
				if (this.Parameters.Contains("UpstreamBranch"))
				{
					return ((string)(this.Parameters["UpstreamBranch"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["UpstreamBranch"] = value;
			}
		}
		
		public string SolutionUniqueName
		{
			get
			{
				if (this.Parameters.Contains("SolutionUniqueName"))
				{
					return ((string)(this.Parameters["SolutionUniqueName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionUniqueName"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.OptionSetValue ConnectionType
		{
			get
			{
				if (this.Parameters.Contains("ConnectionType"))
				{
					return ((Microsoft.Xrm.Sdk.OptionSetValue)(this.Parameters["ConnectionType"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.OptionSetValue);
				}
			}
			set
			{
				this.Parameters["ConnectionType"] = value;
			}
		}
		
		public string RootFolder
		{
			get
			{
				if (this.Parameters.Contains("RootFolder"))
				{
					return ((string)(this.Parameters["RootFolder"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RootFolder"] = value;
			}
		}
		
		public string Branch
		{
			get
			{
				if (this.Parameters.Contains("Branch"))
				{
					return ((string)(this.Parameters["Branch"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Branch"] = value;
			}
		}
		
		public string Project
		{
			get
			{
				if (this.Parameters.Contains("Project"))
				{
					return ((string)(this.Parameters["Project"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Project"] = value;
			}
		}
		
		public string GitFolder
		{
			get
			{
				if (this.Parameters.Contains("GitFolder"))
				{
					return ((string)(this.Parameters["GitFolder"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["GitFolder"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.OptionSetValue GitProvider
		{
			get
			{
				if (this.Parameters.Contains("GitProvider"))
				{
					return ((Microsoft.Xrm.Sdk.OptionSetValue)(this.Parameters["GitProvider"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.OptionSetValue);
				}
			}
			set
			{
				this.Parameters["GitProvider"] = value;
			}
		}
		
		public string Repository
		{
			get
			{
				if (this.Parameters.Contains("Repository"))
				{
					return ((string)(this.Parameters["Repository"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Repository"] = value;
			}
		}
		
		public ConnectToGitRequest()
		{
			this.RequestName = "ConnectToGit";
			this.Branch = default(string);
			this.GitFolder = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ConnectToGit")]
	public partial class ConnectToGitResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "ConnectToGit";
		
		public ConnectToGitResponse()
		{
		}
	}
}
#pragma warning restore CS1591
