#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CreateHostedFlowMachineGroup")]
	public partial class CreateHostedFlowMachineGroupRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string groupCapacityCount = "groupCapacityCount";
			public const string groupMachineNetworkId = "groupMachineNetworkId";
			public const string groupCredentials = "groupCredentials";
			public const string groupImage = "groupImage";
			public const string groupName = "groupName";
			public const string groupDescription = "groupDescription";
			public const string groupMaximumMachineCount = "groupMaximumMachineCount";
			public const string groupDomainSetting = "groupDomainSetting";
		}
		
		public const string ActionLogicalName = "CreateHostedFlowMachineGroup";
		
		public int groupCapacityCount
		{
			get
			{
				if (this.Parameters.Contains("groupCapacityCount"))
				{
					return ((int)(this.Parameters["groupCapacityCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["groupCapacityCount"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference groupMachineNetworkId
		{
			get
			{
				if (this.Parameters.Contains("groupMachineNetworkId"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["groupMachineNetworkId"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["groupMachineNetworkId"] = value;
			}
		}
		
		public string groupCredentials
		{
			get
			{
				if (this.Parameters.Contains("groupCredentials"))
				{
					return ((string)(this.Parameters["groupCredentials"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["groupCredentials"] = value;
			}
		}
		
		public string groupImage
		{
			get
			{
				if (this.Parameters.Contains("groupImage"))
				{
					return ((string)(this.Parameters["groupImage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["groupImage"] = value;
			}
		}
		
		public string groupName
		{
			get
			{
				if (this.Parameters.Contains("groupName"))
				{
					return ((string)(this.Parameters["groupName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["groupName"] = value;
			}
		}
		
		public string groupDescription
		{
			get
			{
				if (this.Parameters.Contains("groupDescription"))
				{
					return ((string)(this.Parameters["groupDescription"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["groupDescription"] = value;
			}
		}
		
		public int groupMaximumMachineCount
		{
			get
			{
				if (this.Parameters.Contains("groupMaximumMachineCount"))
				{
					return ((int)(this.Parameters["groupMaximumMachineCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["groupMaximumMachineCount"] = value;
			}
		}
		
		public string groupDomainSetting
		{
			get
			{
				if (this.Parameters.Contains("groupDomainSetting"))
				{
					return ((string)(this.Parameters["groupDomainSetting"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["groupDomainSetting"] = value;
			}
		}
		
		public CreateHostedFlowMachineGroupRequest()
		{
			this.RequestName = "CreateHostedFlowMachineGroup";
			this.groupCredentials = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CreateHostedFlowMachineGroup")]
	public partial class CreateHostedFlowMachineGroupResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string flowMachineGroupId = "flowMachineGroupId";
			public const string response = "response";
		}
		
		public const string ActionLogicalName = "CreateHostedFlowMachineGroup";
		
		public CreateHostedFlowMachineGroupResponse()
		{
		}
		
		public System.Guid flowMachineGroupId
		{
			get
			{
				if (this.Results.Contains("flowMachineGroupId"))
				{
					return ((System.Guid)(this.Results["flowMachineGroupId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["flowMachineGroupId"] = value;
			}
		}
		
		public string response
		{
			get
			{
				if (this.Results.Contains("response"))
				{
					return ((string)(this.Results["response"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["response"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
