#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CreateRoleWithPrivilegeCheckerRun")]
	public partial class CreateRoleWithPrivilegeCheckerRunRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RoleName = "RoleName";
			public const string PrivilegeCheckerRunId = "PrivilegeCheckerRunId";
		}
		
		public const string ActionLogicalName = "CreateRoleWithPrivilegeCheckerRun";
		
		public string RoleName
		{
			get
			{
				if (this.Parameters.Contains("RoleName"))
				{
					return ((string)(this.Parameters["RoleName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RoleName"] = value;
			}
		}
		
		public System.Guid PrivilegeCheckerRunId
		{
			get
			{
				if (this.Parameters.Contains("PrivilegeCheckerRunId"))
				{
					return ((System.Guid)(this.Parameters["PrivilegeCheckerRunId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["PrivilegeCheckerRunId"] = value;
			}
		}
		
		public CreateRoleWithPrivilegeCheckerRunRequest()
		{
			this.RequestName = "CreateRoleWithPrivilegeCheckerRun";
			this.RoleName = default(string);
			this.PrivilegeCheckerRunId = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CreateRoleWithPrivilegeCheckerRun")]
	public partial class CreateRoleWithPrivilegeCheckerRunResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string RoleId = "RoleId";
		}
		
		public const string ActionLogicalName = "CreateRoleWithPrivilegeCheckerRun";
		
		public CreateRoleWithPrivilegeCheckerRunResponse()
		{
		}
		
		public System.Guid RoleId
		{
			get
			{
				if (this.Results.Contains("RoleId"))
				{
					return ((System.Guid)(this.Results["RoleId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["RoleId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
