#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CreateFlowCredentialApplication")]
	public partial class CreateFlowCredentialApplicationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
			public const string applicationId = "applicationId";
			public const string password = "password";
			public const string certificate = "certificate";
			public const string description = "description";
			public const string sharingtype = "sharingtype";
		}
		
		public const string ActionLogicalName = "CreateFlowCredentialApplication";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string applicationId
		{
			get
			{
				if (this.Parameters.Contains("applicationId"))
				{
					return ((string)(this.Parameters["applicationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["applicationId"] = value;
			}
		}
		
		public string password
		{
			get
			{
				if (this.Parameters.Contains("password"))
				{
					return ((string)(this.Parameters["password"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["password"] = value;
			}
		}
		
		public string certificate
		{
			get
			{
				if (this.Parameters.Contains("certificate"))
				{
					return ((string)(this.Parameters["certificate"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["certificate"] = value;
			}
		}
		
		public string description
		{
			get
			{
				if (this.Parameters.Contains("description"))
				{
					return ((string)(this.Parameters["description"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["description"] = value;
			}
		}
		
		public string sharingtype
		{
			get
			{
				if (this.Parameters.Contains("sharingtype"))
				{
					return ((string)(this.Parameters["sharingtype"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["sharingtype"] = value;
			}
		}
		
		public CreateFlowCredentialApplicationRequest()
		{
			this.RequestName = "CreateFlowCredentialApplication";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.applicationId = default(string);
			this.certificate = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CreateFlowCredentialApplication")]
	public partial class CreateFlowCredentialApplicationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string flowCredentialApplicationId = "flowCredentialApplicationId";
		}
		
		public const string ActionLogicalName = "CreateFlowCredentialApplication";
		
		public CreateFlowCredentialApplicationResponse()
		{
		}
		
		public System.Guid flowCredentialApplicationId
		{
			get
			{
				if (this.Results.Contains("flowCredentialApplicationId"))
				{
					return ((System.Guid)(this.Results["flowCredentialApplicationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["flowCredentialApplicationId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
