#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CreateFlowMachineNetwork")]
	public partial class CreateFlowMachineNetworkRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string supportedscenario = "supportedscenario";
			public const string name = "name";
			public const string description = "description";
			public const string type = "type";
			public const string subnet = "subnet";
			public const string extendedproperties = "extendedproperties";
		}
		
		public const string ActionLogicalName = "CreateFlowMachineNetwork";
		
		public string supportedscenario
		{
			get
			{
				if (this.Parameters.Contains("supportedscenario"))
				{
					return ((string)(this.Parameters["supportedscenario"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["supportedscenario"] = value;
			}
		}
		
		public string name
		{
			get
			{
				if (this.Parameters.Contains("name"))
				{
					return ((string)(this.Parameters["name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["name"] = value;
			}
		}
		
		public string description
		{
			get
			{
				if (this.Parameters.Contains("description"))
				{
					return ((string)(this.Parameters["description"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["description"] = value;
			}
		}
		
		public string type
		{
			get
			{
				if (this.Parameters.Contains("type"))
				{
					return ((string)(this.Parameters["type"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["type"] = value;
			}
		}
		
		public string subnet
		{
			get
			{
				if (this.Parameters.Contains("subnet"))
				{
					return ((string)(this.Parameters["subnet"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["subnet"] = value;
			}
		}
		
		public string extendedproperties
		{
			get
			{
				if (this.Parameters.Contains("extendedproperties"))
				{
					return ((string)(this.Parameters["extendedproperties"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["extendedproperties"] = value;
			}
		}
		
		public CreateFlowMachineNetworkRequest()
		{
			this.RequestName = "CreateFlowMachineNetwork";
			this.supportedscenario = default(string);
			this.name = default(string);
			this.type = default(string);
			this.subnet = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CreateFlowMachineNetwork")]
	public partial class CreateFlowMachineNetworkResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string flowmachinenetworkid = "flowmachinenetworkid";
		}
		
		public const string ActionLogicalName = "CreateFlowMachineNetwork";
		
		public CreateFlowMachineNetworkResponse()
		{
		}
		
		public System.Guid flowmachinenetworkid
		{
			get
			{
				if (this.Results.Contains("flowmachinenetworkid"))
				{
					return ((System.Guid)(this.Results["flowmachinenetworkid"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["flowmachinenetworkid"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
