#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CreateAndSendNewEmail")]
	public partial class CreateAndSendNewEmailRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Subject = "Subject";
			public const string Cc = "Cc";
			public const string From = "From";
			public const string Regarding = "Regarding";
			public const string To = "To";
			public const string Importance = "Importance";
			public const string Bcc = "Bcc";
			public const string Body = "Body";
		}
		
		public const string ActionLogicalName = "CreateAndSendNewEmail";
		
		public string Subject
		{
			get
			{
				if (this.Parameters.Contains("Subject"))
				{
					return ((string)(this.Parameters["Subject"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Subject"] = value;
			}
		}
		
		public string Cc
		{
			get
			{
				if (this.Parameters.Contains("Cc"))
				{
					return ((string)(this.Parameters["Cc"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Cc"] = value;
			}
		}
		
		public string From
		{
			get
			{
				if (this.Parameters.Contains("From"))
				{
					return ((string)(this.Parameters["From"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["From"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Regarding
		{
			get
			{
				if (this.Parameters.Contains("Regarding"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Regarding"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Regarding"] = value;
			}
		}
		
		public string To
		{
			get
			{
				if (this.Parameters.Contains("To"))
				{
					return ((string)(this.Parameters["To"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["To"] = value;
			}
		}
		
		public System.Nullable<int> Importance
		{
			get
			{
				if (this.Parameters.Contains("Importance"))
				{
					return ((System.Nullable<int>)(this.Parameters["Importance"]));
				}
				else
				{
					return default(System.Nullable<int>);
				}
			}
			set
			{
				this.Parameters["Importance"] = value;
			}
		}
		
		public string Bcc
		{
			get
			{
				if (this.Parameters.Contains("Bcc"))
				{
					return ((string)(this.Parameters["Bcc"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Bcc"] = value;
			}
		}
		
		public string Body
		{
			get
			{
				if (this.Parameters.Contains("Body"))
				{
					return ((string)(this.Parameters["Body"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Body"] = value;
			}
		}
		
		public CreateAndSendNewEmailRequest()
		{
			this.RequestName = "CreateAndSendNewEmail";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CreateAndSendNewEmail")]
	public partial class CreateAndSendNewEmailResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string EmailId = "EmailId";
		}
		
		public const string ActionLogicalName = "CreateAndSendNewEmail";
		
		public CreateAndSendNewEmailResponse()
		{
		}
		
		public System.Guid EmailId
		{
			get
			{
				if (this.Results.Contains("EmailId"))
				{
					return ((System.Guid)(this.Results["EmailId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["EmailId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
