#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("Dequeue")]
	public partial class DequeueRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
			public const string request = "request";
		}
		
		public const string ActionLogicalName = "Dequeue";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string request
		{
			get
			{
				if (this.Parameters.Contains("request"))
				{
					return ((string)(this.Parameters["request"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["request"] = value;
			}
		}
		
		public DequeueRequest()
		{
			this.RequestName = "Dequeue";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("Dequeue")]
	public partial class DequeueResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string nextItem = "nextItem";
		}
		
		public const string ActionLogicalName = "Dequeue";
		
		public DequeueResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity nextItem
		{
			get
			{
				if (this.Results.Contains("nextItem"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["nextItem"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["nextItem"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
