#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("DisconnectFromGit")]
	public partial class DisconnectFromGitRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SolutionUniqueName = "SolutionUniqueName";
		}
		
		public const string ActionLogicalName = "DisconnectFromGit";
		
		public string SolutionUniqueName
		{
			get
			{
				if (this.Parameters.Contains("SolutionUniqueName"))
				{
					return ((string)(this.Parameters["SolutionUniqueName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionUniqueName"] = value;
			}
		}
		
		public DisconnectFromGitRequest()
		{
			this.RequestName = "DisconnectFromGit";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("DisconnectFromGit")]
	public partial class DisconnectFromGitResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "DisconnectFromGit";
		
		public DisconnectFromGitResponse()
		{
		}
	}
}
#pragma warning restore CS1591
