#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("DiscoverFabricAISkills")]
	public partial class DiscoverFabricAISkillsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string workspaceId = "workspaceId";
			public const string fabricEnvironment = "fabricEnvironment";
		}
		
		public const string ActionLogicalName = "DiscoverFabricAISkills";
		
		public string workspaceId
		{
			get
			{
				if (this.Parameters.Contains("workspaceId"))
				{
					return ((string)(this.Parameters["workspaceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["workspaceId"] = value;
			}
		}
		
		public string fabricEnvironment
		{
			get
			{
				if (this.Parameters.Contains("fabricEnvironment"))
				{
					return ((string)(this.Parameters["fabricEnvironment"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["fabricEnvironment"] = value;
			}
		}
		
		public DiscoverFabricAISkillsRequest()
		{
			this.RequestName = "DiscoverFabricAISkills";
			this.workspaceId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("DiscoverFabricAISkills")]
	public partial class DiscoverFabricAISkillsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string fabricAISkills = "fabricAISkills";
		}
		
		public const string ActionLogicalName = "DiscoverFabricAISkills";
		
		public DiscoverFabricAISkillsResponse()
		{
		}
		
		public string fabricAISkills
		{
			get
			{
				if (this.Results.Contains("fabricAISkills"))
				{
					return ((string)(this.Results["fabricAISkills"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["fabricAISkills"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
