#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("DiscoverFabricWorkspaces")]
	public partial class DiscoverFabricWorkspacesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string fabricEnvironment = "fabricEnvironment";
		}
		
		public const string ActionLogicalName = "DiscoverFabricWorkspaces";
		
		public string fabricEnvironment
		{
			get
			{
				if (this.Parameters.Contains("fabricEnvironment"))
				{
					return ((string)(this.Parameters["fabricEnvironment"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["fabricEnvironment"] = value;
			}
		}
		
		public DiscoverFabricWorkspacesRequest()
		{
			this.RequestName = "DiscoverFabricWorkspaces";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("DiscoverFabricWorkspaces")]
	public partial class DiscoverFabricWorkspacesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string fabricWorkspaces = "fabricWorkspaces";
		}
		
		public const string ActionLogicalName = "DiscoverFabricWorkspaces";
		
		public DiscoverFabricWorkspacesResponse()
		{
		}
		
		public string fabricWorkspaces
		{
			get
			{
				if (this.Results.Contains("fabricWorkspaces"))
				{
					return ((string)(this.Results["fabricWorkspaces"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["fabricWorkspaces"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
