#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ExecuteBackgroundOperation")]
	public partial class ExecuteBackgroundOperationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Request = "Request";
			public const string CallbackUri = "CallbackUri";
		}
		
		public const string ActionLogicalName = "ExecuteBackgroundOperation";
		
		public Microsoft.Xrm.Sdk.OrganizationRequest Request
		{
			get
			{
				if (this.Parameters.Contains("Request"))
				{
					return ((Microsoft.Xrm.Sdk.OrganizationRequest)(this.Parameters["Request"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.OrganizationRequest);
				}
			}
			set
			{
				this.Parameters["Request"] = value;
			}
		}
		
		public string CallbackUri
		{
			get
			{
				if (this.Parameters.Contains("CallbackUri"))
				{
					return ((string)(this.Parameters["CallbackUri"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CallbackUri"] = value;
			}
		}
		
		public ExecuteBackgroundOperationRequest()
		{
			this.RequestName = "ExecuteBackgroundOperation";
			this.Request = default(Microsoft.Xrm.Sdk.OrganizationRequest);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ExecuteBackgroundOperation")]
	public partial class ExecuteBackgroundOperationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string BackgroundOperationId = "BackgroundOperationId";
			public const string Location = "Location";
		}
		
		public const string ActionLogicalName = "ExecuteBackgroundOperation";
		
		public ExecuteBackgroundOperationResponse()
		{
		}
		
		public System.Guid BackgroundOperationId
		{
			get
			{
				if (this.Results.Contains("BackgroundOperationId"))
				{
					return ((System.Guid)(this.Results["BackgroundOperationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["BackgroundOperationId"] = value;
			}
		}
		
		public string Location
		{
			get
			{
				if (this.Results.Contains("Location"))
				{
					return ((string)(this.Results["Location"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Location"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
