#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ExportSolutionFromGitAsync")]
	public partial class ExportSolutionFromGitAsyncRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Managed = "Managed";
			public const string SolutionName = "SolutionName";
			public const string ReleaseBranch = "ReleaseBranch";
		}
		
		public const string ActionLogicalName = "ExportSolutionFromGitAsync";
		
		public bool Managed
		{
			get
			{
				if (this.Parameters.Contains("Managed"))
				{
					return ((bool)(this.Parameters["Managed"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["Managed"] = value;
			}
		}
		
		public string SolutionName
		{
			get
			{
				if (this.Parameters.Contains("SolutionName"))
				{
					return ((string)(this.Parameters["SolutionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionName"] = value;
			}
		}
		
		public string ReleaseBranch
		{
			get
			{
				if (this.Parameters.Contains("ReleaseBranch"))
				{
					return ((string)(this.Parameters["ReleaseBranch"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ReleaseBranch"] = value;
			}
		}
		
		public ExportSolutionFromGitAsyncRequest()
		{
			this.RequestName = "ExportSolutionFromGitAsync";
			this.Managed = default(bool);
			this.SolutionName = default(string);
			this.ReleaseBranch = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ExportSolutionFromGitAsync")]
	public partial class ExportSolutionFromGitAsyncResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AsyncOperationId = "AsyncOperationId";
			public const string ExportJobId = "ExportJobId";
		}
		
		public const string ActionLogicalName = "ExportSolutionFromGitAsync";
		
		public ExportSolutionFromGitAsyncResponse()
		{
		}
		
		public System.Guid AsyncOperationId
		{
			get
			{
				if (this.Results.Contains("AsyncOperationId"))
				{
					return ((System.Guid)(this.Results["AsyncOperationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["AsyncOperationId"] = value;
			}
		}
		
		public System.Guid ExportJobId
		{
			get
			{
				if (this.Results.Contains("ExportJobId"))
				{
					return ((System.Guid)(this.Results["ExportJobId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["ExportJobId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
