#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ExportSolutionFromGit")]
	public partial class ExportSolutionFromGitRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Managed = "Managed";
			public const string IsLiteExport = "IsLiteExport";
			public const string SolutionName = "SolutionName";
			public const string ReleaseBranch = "ReleaseBranch";
		}
		
		public const string ActionLogicalName = "ExportSolutionFromGit";
		
		public bool Managed
		{
			get
			{
				if (this.Parameters.Contains("Managed"))
				{
					return ((bool)(this.Parameters["Managed"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["Managed"] = value;
			}
		}
		
		public bool IsLiteExport
		{
			get
			{
				if (this.Parameters.Contains("IsLiteExport"))
				{
					return ((bool)(this.Parameters["IsLiteExport"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsLiteExport"] = value;
			}
		}
		
		public string SolutionName
		{
			get
			{
				if (this.Parameters.Contains("SolutionName"))
				{
					return ((string)(this.Parameters["SolutionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionName"] = value;
			}
		}
		
		public string ReleaseBranch
		{
			get
			{
				if (this.Parameters.Contains("ReleaseBranch"))
				{
					return ((string)(this.Parameters["ReleaseBranch"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ReleaseBranch"] = value;
			}
		}
		
		public ExportSolutionFromGitRequest()
		{
			this.RequestName = "ExportSolutionFromGit";
			this.Managed = default(bool);
			this.SolutionName = default(string);
			this.ReleaseBranch = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ExportSolutionFromGit")]
	public partial class ExportSolutionFromGitResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CommitId = "CommitId";
			public const string SolutionZip = "SolutionZip";
		}
		
		public const string ActionLogicalName = "ExportSolutionFromGit";
		
		public ExportSolutionFromGitResponse()
		{
		}
		
		public string CommitId
		{
			get
			{
				if (this.Results.Contains("CommitId"))
				{
					return ((string)(this.Results["CommitId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["CommitId"] = value;
			}
		}
		
		public byte[] SolutionZip
		{
			get
			{
				if (this.Results.Contains("SolutionZip"))
				{
					return ((byte[])(this.Results["SolutionZip"]));
				}
				else
				{
					return default(byte[]);
				}
			}
			set
			{
				this.Results["SolutionZip"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
