#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("FormPredict")]
	public partial class FormPredictRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string context = "context";
			public const string predictorFields = "predictorFields";
			public const string requestedFields = "requestedFields";
			public const string entityName = "entityName";
			public const string recordValues = "recordValues";
			public const string clientPartnerSource = "clientPartnerSource";
		}
		
		public const string ActionLogicalName = "FormPredict";
		
		public string context
		{
			get
			{
				if (this.Parameters.Contains("context"))
				{
					return ((string)(this.Parameters["context"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["context"] = value;
			}
		}
		
		public string[] predictorFields
		{
			get
			{
				if (this.Parameters.Contains("predictorFields"))
				{
					return ((string[])(this.Parameters["predictorFields"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["predictorFields"] = value;
			}
		}
		
		public string[] requestedFields
		{
			get
			{
				if (this.Parameters.Contains("requestedFields"))
				{
					return ((string[])(this.Parameters["requestedFields"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["requestedFields"] = value;
			}
		}
		
		public string entityName
		{
			get
			{
				if (this.Parameters.Contains("entityName"))
				{
					return ((string)(this.Parameters["entityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entityName"] = value;
			}
		}
		
		public string recordValues
		{
			get
			{
				if (this.Parameters.Contains("recordValues"))
				{
					return ((string)(this.Parameters["recordValues"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["recordValues"] = value;
			}
		}
		
		public string clientPartnerSource
		{
			get
			{
				if (this.Parameters.Contains("clientPartnerSource"))
				{
					return ((string)(this.Parameters["clientPartnerSource"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["clientPartnerSource"] = value;
			}
		}
		
		public FormPredictRequest()
		{
			this.RequestName = "FormPredict";
			this.predictorFields = default(string[]);
			this.requestedFields = default(string[]);
			this.entityName = default(string);
			this.recordValues = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("FormPredict")]
	public partial class FormPredictResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string predictionText = "predictionText";
		}
		
		public const string ActionLogicalName = "FormPredict";
		
		public FormPredictResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity predictionText
		{
			get
			{
				if (this.Results.Contains("predictionText"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["predictionText"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["predictionText"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
