#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("GetCertificateCredential")]
	public partial class GetCertificateCredentialRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string entityLogicalName = "entityLogicalName";
			public const string entityId = "entityId";
		}
		
		public const string ActionLogicalName = "GetCertificateCredential";
		
		public string entityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("entityLogicalName"))
				{
					return ((string)(this.Parameters["entityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entityLogicalName"] = value;
			}
		}
		
		public System.Guid entityId
		{
			get
			{
				if (this.Parameters.Contains("entityId"))
				{
					return ((System.Guid)(this.Parameters["entityId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["entityId"] = value;
			}
		}
		
		public GetCertificateCredentialRequest()
		{
			this.RequestName = "GetCertificateCredential";
			this.entityLogicalName = default(string);
			this.entityId = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("GetCertificateCredential")]
	public partial class GetCertificateCredentialResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CertificateCredentials = "CertificateCredentials";
		}
		
		public const string ActionLogicalName = "GetCertificateCredential";
		
		public GetCertificateCredentialResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection CertificateCredentials
		{
			get
			{
				if (this.Results.Contains("CertificateCredentials"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["CertificateCredentials"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["CertificateCredentials"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
