#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("GetHostedRpaCapacity")]
	public partial class GetHostedRpaCapacityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "GetHostedRpaCapacity";
		
		public GetHostedRpaCapacityRequest()
		{
			this.RequestName = "GetHostedRpaCapacity";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("GetHostedRpaCapacity")]
	public partial class GetHostedRpaCapacityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string availableCapacity = "availableCapacity";
			public const string failedToGetCapacity = "failedToGetCapacity";
			public const string hostedGroupCount = "hostedGroupCount";
			public const string hostedMachineCount = "hostedMachineCount";
			public const string hostedMachineGroupsBotCount = "hostedMachineGroupsBotCount";
			public const string isPayGo = "isPayGo";
			public const string totalEnvironmentAddOns = "totalEnvironmentAddOns";
		}
		
		public const string ActionLogicalName = "GetHostedRpaCapacity";
		
		public GetHostedRpaCapacityResponse()
		{
		}
		
		public int availableCapacity
		{
			get
			{
				if (this.Results.Contains("availableCapacity"))
				{
					return ((int)(this.Results["availableCapacity"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["availableCapacity"] = value;
			}
		}
		
		public bool failedToGetCapacity
		{
			get
			{
				if (this.Results.Contains("failedToGetCapacity"))
				{
					return ((bool)(this.Results["failedToGetCapacity"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["failedToGetCapacity"] = value;
			}
		}
		
		public int hostedGroupCount
		{
			get
			{
				if (this.Results.Contains("hostedGroupCount"))
				{
					return ((int)(this.Results["hostedGroupCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["hostedGroupCount"] = value;
			}
		}
		
		public int hostedMachineCount
		{
			get
			{
				if (this.Results.Contains("hostedMachineCount"))
				{
					return ((int)(this.Results["hostedMachineCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["hostedMachineCount"] = value;
			}
		}
		
		public int hostedMachineGroupsBotCount
		{
			get
			{
				if (this.Results.Contains("hostedMachineGroupsBotCount"))
				{
					return ((int)(this.Results["hostedMachineGroupsBotCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["hostedMachineGroupsBotCount"] = value;
			}
		}
		
		public bool isPayGo
		{
			get
			{
				if (this.Results.Contains("isPayGo"))
				{
					return ((bool)(this.Results["isPayGo"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["isPayGo"] = value;
			}
		}
		
		public int totalEnvironmentAddOns
		{
			get
			{
				if (this.Results.Contains("totalEnvironmentAddOns"))
				{
					return ((int)(this.Results["totalEnvironmentAddOns"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["totalEnvironmentAddOns"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
