#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("GetOrCreateSharedWorkspace")]
	public partial class GetOrCreateSharedWorkspaceRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string target = "target";
			public const string customclaims = "customclaims";
		}
		
		public const string ActionLogicalName = "GetOrCreateSharedWorkspace";
		
		public Microsoft.Xrm.Sdk.Entity target
		{
			get
			{
				if (this.Parameters.Contains("target"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["target"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity customclaims
		{
			get
			{
				if (this.Parameters.Contains("customclaims"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["customclaims"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["customclaims"] = value;
			}
		}
		
		public GetOrCreateSharedWorkspaceRequest()
		{
			this.RequestName = "GetOrCreateSharedWorkspace";
			this.target = default(Microsoft.Xrm.Sdk.Entity);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("GetOrCreateSharedWorkspace")]
	public partial class GetOrCreateSharedWorkspaceResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string target = "target";
		}
		
		public const string ActionLogicalName = "GetOrCreateSharedWorkspace";
		
		public GetOrCreateSharedWorkspaceResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity target
		{
			get
			{
				if (this.Results.Contains("target"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["target"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
