#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("GetPBIReportRefreshStatus")]
	public partial class GetPBIReportRefreshStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ReportId = "ReportId";
		}
		
		public const string ActionLogicalName = "GetPBIReportRefreshStatus";
		
		public System.Guid ReportId
		{
			get
			{
				if (this.Parameters.Contains("ReportId"))
				{
					return ((System.Guid)(this.Parameters["ReportId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["ReportId"] = value;
			}
		}
		
		public GetPBIReportRefreshStatusRequest()
		{
			this.RequestName = "GetPBIReportRefreshStatus";
			this.ReportId = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("GetPBIReportRefreshStatus")]
	public partial class GetPBIReportRefreshStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ReportRefreshStatusEndTime = "ReportRefreshStatusEndTime";
			public const string ReportRefreshStatusStartTime = "ReportRefreshStatusStartTime";
			public const string ReportRefreshStatusState = "ReportRefreshStatusState";
		}
		
		public const string ActionLogicalName = "GetPBIReportRefreshStatus";
		
		public GetPBIReportRefreshStatusResponse()
		{
		}
		
		public string ReportRefreshStatusEndTime
		{
			get
			{
				if (this.Results.Contains("ReportRefreshStatusEndTime"))
				{
					return ((string)(this.Results["ReportRefreshStatusEndTime"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ReportRefreshStatusEndTime"] = value;
			}
		}
		
		public string ReportRefreshStatusStartTime
		{
			get
			{
				if (this.Results.Contains("ReportRefreshStatusStartTime"))
				{
					return ((string)(this.Results["ReportRefreshStatusStartTime"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ReportRefreshStatusStartTime"] = value;
			}
		}
		
		public string ReportRefreshStatusState
		{
			get
			{
				if (this.Results.Contains("ReportRefreshStatusState"))
				{
					return ((string)(this.Results["ReportRefreshStatusState"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ReportRefreshStatusState"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
