#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("GetSearchInformation")]
	public partial class GetSearchInformationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Fetchxml = "Fetchxml";
		}
		
		public const string ActionLogicalName = "GetSearchInformation";
		
		public string Fetchxml
		{
			get
			{
				if (this.Parameters.Contains("Fetchxml"))
				{
					return ((string)(this.Parameters["Fetchxml"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Fetchxml"] = value;
			}
		}
		
		public GetSearchInformationRequest()
		{
			this.RequestName = "GetSearchInformation";
			this.Fetchxml = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("GetSearchInformation")]
	public partial class GetSearchInformationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CanAllowLeadingWildCardSearch = "CanAllowLeadingWildCardSearch";
			public const string CanSupportedByRelevanceSearch = "CanSupportedByRelevanceSearch";
		}
		
		public const string ActionLogicalName = "GetSearchInformation";
		
		public GetSearchInformationResponse()
		{
		}
		
		public string CanAllowLeadingWildCardSearch
		{
			get
			{
				if (this.Results.Contains("CanAllowLeadingWildCardSearch"))
				{
					return ((string)(this.Results["CanAllowLeadingWildCardSearch"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["CanAllowLeadingWildCardSearch"] = value;
			}
		}
		
		public string CanSupportedByRelevanceSearch
		{
			get
			{
				if (this.Results.Contains("CanSupportedByRelevanceSearch"))
				{
					return ((string)(this.Results["CanSupportedByRelevanceSearch"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["CanSupportedByRelevanceSearch"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
