#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("InferEntityDefinition")]
	public partial class InferEntityDefinitionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntityDefinition = "EntityDefinition";
			public const string FileInfo = "FileInfo";
			public const string PreviewData = "PreviewData";
			public const string UserContext = "UserContext";
			public const string UseUserSettings = "UseUserSettings";
			public const string LanguageCode = "LanguageCode";
			public const string SourceTimeZone = "SourceTimeZone";
			public const string ParseSampleData = "ParseSampleData";
			public const string RecordId = "RecordId";
			public const string SolutionPrefix = "SolutionPrefix";
			public const string EntitiesCollection = "EntitiesCollection";
		}
		
		public const string ActionLogicalName = "InferEntityDefinition";
		
		public string EntityDefinition
		{
			get
			{
				if (this.Parameters.Contains("EntityDefinition"))
				{
					return ((string)(this.Parameters["EntityDefinition"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityDefinition"] = value;
			}
		}
		
		public string FileInfo
		{
			get
			{
				if (this.Parameters.Contains("FileInfo"))
				{
					return ((string)(this.Parameters["FileInfo"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FileInfo"] = value;
			}
		}
		
		public string PreviewData
		{
			get
			{
				if (this.Parameters.Contains("PreviewData"))
				{
					return ((string)(this.Parameters["PreviewData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PreviewData"] = value;
			}
		}
		
		public string UserContext
		{
			get
			{
				if (this.Parameters.Contains("UserContext"))
				{
					return ((string)(this.Parameters["UserContext"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["UserContext"] = value;
			}
		}
		
		public bool UseUserSettings
		{
			get
			{
				if (this.Parameters.Contains("UseUserSettings"))
				{
					return ((bool)(this.Parameters["UseUserSettings"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["UseUserSettings"] = value;
			}
		}
		
		public int LanguageCode
		{
			get
			{
				if (this.Parameters.Contains("LanguageCode"))
				{
					return ((int)(this.Parameters["LanguageCode"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["LanguageCode"] = value;
			}
		}
		
		public string SourceTimeZone
		{
			get
			{
				if (this.Parameters.Contains("SourceTimeZone"))
				{
					return ((string)(this.Parameters["SourceTimeZone"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SourceTimeZone"] = value;
			}
		}
		
		public bool ParseSampleData
		{
			get
			{
				if (this.Parameters.Contains("ParseSampleData"))
				{
					return ((bool)(this.Parameters["ParseSampleData"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ParseSampleData"] = value;
			}
		}
		
		public System.Guid RecordId
		{
			get
			{
				if (this.Parameters.Contains("RecordId"))
				{
					return ((System.Guid)(this.Parameters["RecordId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["RecordId"] = value;
			}
		}
		
		public string SolutionPrefix
		{
			get
			{
				if (this.Parameters.Contains("SolutionPrefix"))
				{
					return ((string)(this.Parameters["SolutionPrefix"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionPrefix"] = value;
			}
		}
		
		public string EntitiesCollection
		{
			get
			{
				if (this.Parameters.Contains("EntitiesCollection"))
				{
					return ((string)(this.Parameters["EntitiesCollection"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntitiesCollection"] = value;
			}
		}
		
		public InferEntityDefinitionRequest()
		{
			this.RequestName = "InferEntityDefinition";
			this.RecordId = default(System.Guid);
			this.SolutionPrefix = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("InferEntityDefinition")]
	public partial class InferEntityDefinitionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string EntitiesCollection = "EntitiesCollection";
			public const string EntityDefinition = "EntityDefinition";
			public const string FileInfo = "FileInfo";
			public const string SampleData = "SampleData";
			public const string UsingFallbackLogic = "UsingFallbackLogic";
		}
		
		public const string ActionLogicalName = "InferEntityDefinition";
		
		public InferEntityDefinitionResponse()
		{
		}
		
		public string EntitiesCollection
		{
			get
			{
				if (this.Results.Contains("EntitiesCollection"))
				{
					return ((string)(this.Results["EntitiesCollection"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["EntitiesCollection"] = value;
			}
		}
		
		public string EntityDefinition
		{
			get
			{
				if (this.Results.Contains("EntityDefinition"))
				{
					return ((string)(this.Results["EntityDefinition"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["EntityDefinition"] = value;
			}
		}
		
		public string FileInfo
		{
			get
			{
				if (this.Results.Contains("FileInfo"))
				{
					return ((string)(this.Results["FileInfo"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["FileInfo"] = value;
			}
		}
		
		public string SampleData
		{
			get
			{
				if (this.Results.Contains("SampleData"))
				{
					return ((string)(this.Results["SampleData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["SampleData"] = value;
			}
		}
		
		public bool UsingFallbackLogic
		{
			get
			{
				if (this.Results.Contains("UsingFallbackLogic"))
				{
					return ((bool)(this.Results["UsingFallbackLogic"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["UsingFallbackLogic"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
