#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("InitializeTemporaryFileBlocksUpload")]
	public partial class InitializeTemporaryFileBlocksUploadRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string FileSize = "FileSize";
			public const string FileName = "FileName";
		}
		
		public const string ActionLogicalName = "InitializeTemporaryFileBlocksUpload";
		
		public int FileSize
		{
			get
			{
				if (this.Parameters.Contains("FileSize"))
				{
					return ((int)(this.Parameters["FileSize"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["FileSize"] = value;
			}
		}
		
		public string FileName
		{
			get
			{
				if (this.Parameters.Contains("FileName"))
				{
					return ((string)(this.Parameters["FileName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FileName"] = value;
			}
		}
		
		public InitializeTemporaryFileBlocksUploadRequest()
		{
			this.RequestName = "InitializeTemporaryFileBlocksUpload";
			this.FileSize = default(int);
			this.FileName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("InitializeTemporaryFileBlocksUpload")]
	public partial class InitializeTemporaryFileBlocksUploadResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string FileContinuationToken = "FileContinuationToken";
			public const string RecordId = "RecordId";
		}
		
		public const string ActionLogicalName = "InitializeTemporaryFileBlocksUpload";
		
		public InitializeTemporaryFileBlocksUploadResponse()
		{
		}
		
		public string FileContinuationToken
		{
			get
			{
				if (this.Results.Contains("FileContinuationToken"))
				{
					return ((string)(this.Results["FileContinuationToken"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["FileContinuationToken"] = value;
			}
		}
		
		public System.Guid RecordId
		{
			get
			{
				if (this.Results.Contains("RecordId"))
				{
					return ((System.Guid)(this.Results["RecordId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["RecordId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
