#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ListConnectionReferences")]
	public partial class ListConnectionReferencesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "ListConnectionReferences";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ListConnectionReferencesRequest()
		{
			this.RequestName = "ListConnectionReferences";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ListConnectionReferences")]
	public partial class ListConnectionReferencesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string connectionReferences = "connectionReferences";
			public const string connections = "connections";
			public const string mappingBetweenLogicalNameAndName = "mappingBetweenLogicalNameAndName";
		}
		
		public const string ActionLogicalName = "ListConnectionReferences";
		
		public ListConnectionReferencesResponse()
		{
		}
		
		public string connectionReferences
		{
			get
			{
				if (this.Results.Contains("connectionReferences"))
				{
					return ((string)(this.Results["connectionReferences"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["connectionReferences"] = value;
			}
		}
		
		public string connections
		{
			get
			{
				if (this.Results.Contains("connections"))
				{
					return ((string)(this.Results["connections"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["connections"] = value;
			}
		}
		
		public string mappingBetweenLogicalNameAndName
		{
			get
			{
				if (this.Results.Contains("mappingBetweenLogicalNameAndName"))
				{
					return ((string)(this.Results["mappingBetweenLogicalNameAndName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["mappingBetweenLogicalNameAndName"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
