#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("McpCreateTable")]
	public partial class McpCreateTableRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string tablename = "tablename";
			public const string Item_1 = "Item_1";
			public const string displayname = "displayname";
		}
		
		public const string ActionLogicalName = "McpCreateTable";
		
		public string tablename
		{
			get
			{
				if (this.Parameters.Contains("tablename"))
				{
					return ((string)(this.Parameters["tablename"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["tablename"] = value;
			}
		}
		
		public string Item_1
		{
			get
			{
				if (this.Parameters.Contains("item"))
				{
					return ((string)(this.Parameters["item"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["item"] = value;
			}
		}
		
		public string displayname
		{
			get
			{
				if (this.Parameters.Contains("displayname"))
				{
					return ((string)(this.Parameters["displayname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["displayname"] = value;
			}
		}
		
		public McpCreateTableRequest()
		{
			this.RequestName = "McpCreateTable";
			this.tablename = default(string);
			this.Item_1 = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("McpCreateTable")]
	public partial class McpCreateTableResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string successMessage = "successMessage";
		}
		
		public const string ActionLogicalName = "McpCreateTable";
		
		public McpCreateTableResponse()
		{
		}
		
		public string successMessage
		{
			get
			{
				if (this.Results.Contains("successMessage"))
				{
					return ((string)(this.Results["successMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["successMessage"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
