#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_getCTandEACdisabledEntities")]
	public partial class msdyn_getCTandEACdisabledEntitiesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string msdyn_entityList = "msdyn_entityList";
			public const string msdyn_entityName = "msdyn_entityName";
		}
		
		public const string ActionLogicalName = "msdyn_getCTandEACdisabledEntities";
		
		public string msdyn_entityList
		{
			get
			{
				if (this.Parameters.Contains("msdyn_entityList"))
				{
					return ((string)(this.Parameters["msdyn_entityList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_entityList"] = value;
			}
		}
		
		public string msdyn_entityName
		{
			get
			{
				if (this.Parameters.Contains("msdyn_entityName"))
				{
					return ((string)(this.Parameters["msdyn_entityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_entityName"] = value;
			}
		}
		
		public msdyn_getCTandEACdisabledEntitiesRequest()
		{
			this.RequestName = "msdyn_getCTandEACdisabledEntities";
			this.msdyn_entityList = default(string);
			this.msdyn_entityName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_getCTandEACdisabledEntities")]
	public partial class msdyn_getCTandEACdisabledEntitiesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string msdyn_apiResponse = "msdyn_apiResponse";
		}
		
		public const string ActionLogicalName = "msdyn_getCTandEACdisabledEntities";
		
		public msdyn_getCTandEACdisabledEntitiesResponse()
		{
		}
		
		public string msdyn_apiResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_apiResponse"))
				{
					return ((string)(this.Results["msdyn_apiResponse"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["msdyn_apiResponse"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
