#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateNewAnalysisJob")]
	public partial class msdyn_CreateNewAnalysisJobRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ComponentInstances = "ComponentInstances";
		}
		
		public const string ActionLogicalName = "msdyn_CreateNewAnalysisJob";
		
		public Microsoft.Xrm.Sdk.EntityReferenceCollection ComponentInstances
		{
			get
			{
				if (this.Parameters.Contains("ComponentInstances"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReferenceCollection)(this.Parameters["ComponentInstances"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReferenceCollection);
				}
			}
			set
			{
				this.Parameters["ComponentInstances"] = value;
			}
		}
		
		public msdyn_CreateNewAnalysisJobRequest()
		{
			this.RequestName = "msdyn_CreateNewAnalysisJob";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CreateNewAnalysisJob")]
	public partial class msdyn_CreateNewAnalysisJobResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CreatedAnalysisJob = "CreatedAnalysisJob";
		}
		
		public const string ActionLogicalName = "msdyn_CreateNewAnalysisJob";
		
		public msdyn_CreateNewAnalysisJobResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference CreatedAnalysisJob
		{
			get
			{
				if (this.Results.Contains("CreatedAnalysisJob"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["CreatedAnalysisJob"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Results["CreatedAnalysisJob"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
