#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_MigrateSlaProactiveRun")]
	public partial class msdyn_MigrateSlaProactiveRunRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "msdyn_MigrateSlaProactiveRun";
		
		public msdyn_MigrateSlaProactiveRunRequest()
		{
			this.RequestName = "msdyn_MigrateSlaProactiveRun";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_MigrateSlaProactiveRun")]
	public partial class msdyn_MigrateSlaProactiveRunResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Exception = "Exception";
			public const string OutputString = "OutputString";
		}
		
		public const string ActionLogicalName = "msdyn_MigrateSlaProactiveRun";
		
		public msdyn_MigrateSlaProactiveRunResponse()
		{
		}
		
		public string Exception
		{
			get
			{
				if (this.Results.Contains("Exception"))
				{
					return ((string)(this.Results["Exception"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Exception"] = value;
			}
		}
		
		public string OutputString
		{
			get
			{
				if (this.Results.Contains("OutputString"))
				{
					return ((string)(this.Results["OutputString"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["OutputString"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
