#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ModelAppRepair")]
	public partial class msdyn_ModelAppRepairRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string AnalysisResult = "AnalysisResult";
		}
		
		public const string ActionLogicalName = "msdyn_ModelAppRepair";
		
		public Microsoft.Xrm.Sdk.EntityReference AnalysisResult
		{
			get
			{
				if (this.Parameters.Contains("AnalysisResult"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["AnalysisResult"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["AnalysisResult"] = value;
			}
		}
		
		public msdyn_ModelAppRepairRequest()
		{
			this.RequestName = "msdyn_ModelAppRepair";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ModelAppRepair")]
	public partial class msdyn_ModelAppRepairResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string HelpLink = "HelpLink";
			public const string ResolutionState = "ResolutionState";
			public const string ResolvedRecordsCount = "ResolvedRecordsCount";
		}
		
		public const string ActionLogicalName = "msdyn_ModelAppRepair";
		
		public msdyn_ModelAppRepairResponse()
		{
		}
		
		public string HelpLink
		{
			get
			{
				if (this.Results.Contains("HelpLink"))
				{
					return ((string)(this.Results["HelpLink"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["HelpLink"] = value;
			}
		}
		
		public int ResolutionState
		{
			get
			{
				if (this.Results.Contains("ResolutionState"))
				{
					return ((int)(this.Results["ResolutionState"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ResolutionState"] = value;
			}
		}
		
		public int ResolvedRecordsCount
		{
			get
			{
				if (this.Results.Contains("ResolvedRecordsCount"))
				{
					return ((int)(this.Results["ResolvedRecordsCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ResolvedRecordsCount"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
