#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_TriggerIntegratedSearchIngestion")]
	public partial class msdyn_TriggerIntegratedSearchIngestionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "msdyn_TriggerIntegratedSearchIngestion";
		
		public msdyn_TriggerIntegratedSearchIngestionRequest()
		{
			this.RequestName = "msdyn_TriggerIntegratedSearchIngestion";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_TriggerIntegratedSearchIngestion")]
	public partial class msdyn_TriggerIntegratedSearchIngestionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string msdyn_IntegratedSearchIngestionResponse = "msdyn_IntegratedSearchIngestionResponse";
		}
		
		public const string ActionLogicalName = "msdyn_TriggerIntegratedSearchIngestion";
		
		public msdyn_TriggerIntegratedSearchIngestionResponse()
		{
		}
		
		public string msdyn_IntegratedSearchIngestionResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_IntegratedSearchIngestionResponse"))
				{
					return ((string)(this.Results["msdyn_IntegratedSearchIngestionResponse"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["msdyn_IntegratedSearchIngestionResponse"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
