#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_TriggerIntegratedSearchSync")]
	public partial class msdyn_TriggerIntegratedSearchSyncRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "msdyn_TriggerIntegratedSearchSync";
		
		public msdyn_TriggerIntegratedSearchSyncRequest()
		{
			this.RequestName = "msdyn_TriggerIntegratedSearchSync";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_TriggerIntegratedSearchSync")]
	public partial class msdyn_TriggerIntegratedSearchSyncResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string msdyn_IntegratedSearchSyncResponse = "msdyn_IntegratedSearchSyncResponse";
		}
		
		public const string ActionLogicalName = "msdyn_TriggerIntegratedSearchSync";
		
		public msdyn_TriggerIntegratedSearchSyncResponse()
		{
		}
		
		public string msdyn_IntegratedSearchSyncResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_IntegratedSearchSyncResponse"))
				{
					return ((string)(this.Results["msdyn_IntegratedSearchSyncResponse"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["msdyn_IntegratedSearchSyncResponse"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
