#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_dataprovideroperations")]
	public partial class msdyn_dataprovideroperationsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string msdyn_httpmethod = "msdyn_httpmethod";
			public const string msdyn_payload = "msdyn_payload";
			public const string msdyn_recordid = "msdyn_recordid";
		}
		
		public const string ActionLogicalName = "msdyn_dataprovideroperations";
		
		public string msdyn_httpmethod
		{
			get
			{
				if (this.Parameters.Contains("msdyn_httpmethod"))
				{
					return ((string)(this.Parameters["msdyn_httpmethod"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_httpmethod"] = value;
			}
		}
		
		public string msdyn_payload
		{
			get
			{
				if (this.Parameters.Contains("msdyn_payload"))
				{
					return ((string)(this.Parameters["msdyn_payload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_payload"] = value;
			}
		}
		
		public string msdyn_recordid
		{
			get
			{
				if (this.Parameters.Contains("msdyn_recordid"))
				{
					return ((string)(this.Parameters["msdyn_recordid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_recordid"] = value;
			}
		}
		
		public msdyn_dataprovideroperationsRequest()
		{
			this.RequestName = "msdyn_dataprovideroperations";
			this.msdyn_httpmethod = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_dataprovideroperations")]
	public partial class msdyn_dataprovideroperationsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string msdyn_response = "msdyn_response";
		}
		
		public const string ActionLogicalName = "msdyn_dataprovideroperations";
		
		public msdyn_dataprovideroperationsResponse()
		{
		}
		
		public string msdyn_response
		{
			get
			{
				if (this.Results.Contains("msdyn_response"))
				{
					return ((string)(this.Results["msdyn_response"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["msdyn_response"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
