#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_FixSLARelationshipsOnTargetEntities")]
	public partial class msdyn_FixSLARelationshipsOnTargetEntitiesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SLAEnabledEnitiesToProcess = "SLAEnabledEnitiesToProcess";
		}
		
		public const string ActionLogicalName = "msdyn_FixSLARelationshipsOnTargetEntities";
		
		public string SLAEnabledEnitiesToProcess
		{
			get
			{
				if (this.Parameters.Contains("SLAEnabledEnitiesToProcess"))
				{
					return ((string)(this.Parameters["SLAEnabledEnitiesToProcess"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SLAEnabledEnitiesToProcess"] = value;
			}
		}
		
		public msdyn_FixSLARelationshipsOnTargetEntitiesRequest()
		{
			this.RequestName = "msdyn_FixSLARelationshipsOnTargetEntities";
			this.SLAEnabledEnitiesToProcess = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_FixSLARelationshipsOnTargetEntities")]
	public partial class msdyn_FixSLARelationshipsOnTargetEntitiesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "msdyn_FixSLARelationshipsOnTargetEntities";
		
		public msdyn_FixSLARelationshipsOnTargetEntitiesResponse()
		{
		}
	}
}
#pragma warning restore CS1591
