#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ResolveSolutionHealthRuleFailure")]
	public partial class msdyn_ResolveSolutionHealthRuleFailureRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string AnalysisResult = "AnalysisResult";
		}
		
		public const string ActionLogicalName = "msdyn_ResolveSolutionHealthRuleFailure";
		
		public Microsoft.Xrm.Sdk.EntityReference AnalysisResult
		{
			get
			{
				if (this.Parameters.Contains("AnalysisResult"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["AnalysisResult"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["AnalysisResult"] = value;
			}
		}
		
		public msdyn_ResolveSolutionHealthRuleFailureRequest()
		{
			this.RequestName = "msdyn_ResolveSolutionHealthRuleFailure";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ResolveSolutionHealthRuleFailure")]
	public partial class msdyn_ResolveSolutionHealthRuleFailureResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "msdyn_ResolveSolutionHealthRuleFailure";
		
		public msdyn_ResolveSolutionHealthRuleFailureResponse()
		{
		}
	}
}
#pragma warning restore CS1591
