#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_LoadCalendars")]
	public partial class msdyn_LoadCalendarsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string LoadCalendarsInput = "LoadCalendarsInput";
		}
		
		public const string ActionLogicalName = "msdyn_LoadCalendars";
		
		public string LoadCalendarsInput
		{
			get
			{
				if (this.Parameters.Contains("LoadCalendarsInput"))
				{
					return ((string)(this.Parameters["LoadCalendarsInput"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LoadCalendarsInput"] = value;
			}
		}
		
		public msdyn_LoadCalendarsRequest()
		{
			this.RequestName = "msdyn_LoadCalendars";
			this.LoadCalendarsInput = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_LoadCalendars")]
	public partial class msdyn_LoadCalendarsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CalendarEvents = "CalendarEvents";
		}
		
		public const string ActionLogicalName = "msdyn_LoadCalendars";
		
		public msdyn_LoadCalendarsResponse()
		{
		}
		
		public string CalendarEvents
		{
			get
			{
				if (this.Results.Contains("CalendarEvents"))
				{
					return ((string)(this.Results["CalendarEvents"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["CalendarEvents"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
