#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_MobileAppBuildStatus")]
	public partial class msdyn_MobileAppBuildStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string msdyn_MobileApp = "msdyn_MobileApp";
			public const string OperationId = "OperationId";
		}
		
		public const string ActionLogicalName = "msdyn_MobileAppBuildStatus";
		
		public Microsoft.Xrm.Sdk.EntityReference msdyn_MobileApp
		{
			get
			{
				if (this.Parameters.Contains("msdyn_MobileApp"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["msdyn_MobileApp"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["msdyn_MobileApp"] = value;
			}
		}
		
		public string OperationId
		{
			get
			{
				if (this.Parameters.Contains("OperationId"))
				{
					return ((string)(this.Parameters["OperationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["OperationId"] = value;
			}
		}
		
		public msdyn_MobileAppBuildStatusRequest()
		{
			this.RequestName = "msdyn_MobileAppBuildStatus";
			this.msdyn_MobileApp = default(Microsoft.Xrm.Sdk.EntityReference);
			this.OperationId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_MobileAppBuildStatus")]
	public partial class msdyn_MobileAppBuildStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "msdyn_MobileAppBuildStatus";
		
		public msdyn_MobileAppBuildStatusResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
