#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ValidateKeyVault")]
	public partial class msdyn_ValidateKeyVaultRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string PlatformType = "PlatformType";
			public const string KeyVaultUri = "KeyVaultUri";
			public const string BundleIdentifier = "BundleIdentifier";
			public const string StorageTypeForUpload = "StorageTypeForUpload";
			public const string IsAppSigningEnabled = "IsAppSigningEnabled";
		}
		
		public const string ActionLogicalName = "msdyn_ValidateKeyVault";
		
		public string PlatformType
		{
			get
			{
				if (this.Parameters.Contains("PlatformType"))
				{
					return ((string)(this.Parameters["PlatformType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PlatformType"] = value;
			}
		}
		
		public string KeyVaultUri
		{
			get
			{
				if (this.Parameters.Contains("KeyVaultUri"))
				{
					return ((string)(this.Parameters["KeyVaultUri"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["KeyVaultUri"] = value;
			}
		}
		
		public string BundleIdentifier
		{
			get
			{
				if (this.Parameters.Contains("BundleIdentifier"))
				{
					return ((string)(this.Parameters["BundleIdentifier"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BundleIdentifier"] = value;
			}
		}
		
		public string StorageTypeForUpload
		{
			get
			{
				if (this.Parameters.Contains("StorageTypeForUpload"))
				{
					return ((string)(this.Parameters["StorageTypeForUpload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["StorageTypeForUpload"] = value;
			}
		}
		
		public bool IsAppSigningEnabled
		{
			get
			{
				if (this.Parameters.Contains("IsAppSigningEnabled"))
				{
					return ((bool)(this.Parameters["IsAppSigningEnabled"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsAppSigningEnabled"] = value;
			}
		}
		
		public msdyn_ValidateKeyVaultRequest()
		{
			this.RequestName = "msdyn_ValidateKeyVault";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ValidateKeyVault")]
	public partial class msdyn_ValidateKeyVaultResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "msdyn_ValidateKeyVault";
		
		public msdyn_ValidateKeyVaultResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
