#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CheckIfFormsHaveTooManyCustomControls")]
	public partial class msdyn_CheckIfFormsHaveTooManyCustomControlsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SolutionName = "SolutionName";
			public const string LogicalNamesOfEntitiesToCheck = "LogicalNamesOfEntitiesToCheck";
			public const string NotificationRecipientUserIds = "NotificationRecipientUserIds";
			public const string ControlsAndLimits = "ControlsAndLimits";
		}
		
		public const string ActionLogicalName = "msdyn_CheckIfFormsHaveTooManyCustomControls";
		
		public string SolutionName
		{
			get
			{
				if (this.Parameters.Contains("SolutionName"))
				{
					return ((string)(this.Parameters["SolutionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionName"] = value;
			}
		}
		
		public string LogicalNamesOfEntitiesToCheck
		{
			get
			{
				if (this.Parameters.Contains("LogicalNamesOfEntitiesToCheck"))
				{
					return ((string)(this.Parameters["LogicalNamesOfEntitiesToCheck"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LogicalNamesOfEntitiesToCheck"] = value;
			}
		}
		
		public string NotificationRecipientUserIds
		{
			get
			{
				if (this.Parameters.Contains("NotificationRecipientUserIds"))
				{
					return ((string)(this.Parameters["NotificationRecipientUserIds"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["NotificationRecipientUserIds"] = value;
			}
		}
		
		public string ControlsAndLimits
		{
			get
			{
				if (this.Parameters.Contains("ControlsAndLimits"))
				{
					return ((string)(this.Parameters["ControlsAndLimits"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ControlsAndLimits"] = value;
			}
		}
		
		public msdyn_CheckIfFormsHaveTooManyCustomControlsRequest()
		{
			this.RequestName = "msdyn_CheckIfFormsHaveTooManyCustomControls";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CheckIfFormsHaveTooManyCustomControls")]
	public partial class msdyn_CheckIfFormsHaveTooManyCustomControlsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string HelpLink = "HelpLink";
			public const string Message = "Message";
			public const string ResultEntities = "ResultEntities";
			public const string ReturnSeverity = "ReturnSeverity";
			public const string ReturnStatus = "ReturnStatus";
		}
		
		public const string ActionLogicalName = "msdyn_CheckIfFormsHaveTooManyCustomControls";
		
		public msdyn_CheckIfFormsHaveTooManyCustomControlsResponse()
		{
		}
		
		public string HelpLink
		{
			get
			{
				if (this.Results.Contains("HelpLink"))
				{
					return ((string)(this.Results["HelpLink"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["HelpLink"] = value;
			}
		}
		
		public string Message
		{
			get
			{
				if (this.Results.Contains("Message"))
				{
					return ((string)(this.Results["Message"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Message"] = value;
			}
		}
		
		public string ResultEntities
		{
			get
			{
				if (this.Results.Contains("ResultEntities"))
				{
					return ((string)(this.Results["ResultEntities"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ResultEntities"] = value;
			}
		}
		
		public int ReturnSeverity
		{
			get
			{
				if (this.Results.Contains("ReturnSeverity"))
				{
					return ((int)(this.Results["ReturnSeverity"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ReturnSeverity"] = value;
			}
		}
		
		public int ReturnStatus
		{
			get
			{
				if (this.Results.Contains("ReturnStatus"))
				{
					return ((int)(this.Results["ReturnStatus"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ReturnStatus"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
