#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetSubjectHierarchyData")]
	public partial class msdyn_GetSubjectHierarchyDataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string input = "input";
		}
		
		public const string ActionLogicalName = "msdyn_GetSubjectHierarchyData";
		
		public string input
		{
			get
			{
				if (this.Parameters.Contains("input"))
				{
					return ((string)(this.Parameters["input"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["input"] = value;
			}
		}
		
		public msdyn_GetSubjectHierarchyDataRequest()
		{
			this.RequestName = "msdyn_GetSubjectHierarchyData";
			this.input = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetSubjectHierarchyData")]
	public partial class msdyn_GetSubjectHierarchyDataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string output = "output";
		}
		
		public const string ActionLogicalName = "msdyn_GetSubjectHierarchyData";
		
		public msdyn_GetSubjectHierarchyDataResponse()
		{
		}
		
		public string output
		{
			get
			{
				if (this.Results.Contains("output"))
				{
					return ((string)(this.Results["output"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["output"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
