#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_BulkAITestRun")]
	public partial class msdyn_BulkAITestRunRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string request = "request";
		}
		
		public const string ActionLogicalName = "msdyn_BulkAITestRun";
		
		public string request
		{
			get
			{
				if (this.Parameters.Contains("request"))
				{
					return ((string)(this.Parameters["request"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["request"] = value;
			}
		}
		
		public msdyn_BulkAITestRunRequest()
		{
			this.RequestName = "msdyn_BulkAITestRun";
			this.request = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_BulkAITestRun")]
	public partial class msdyn_BulkAITestRunResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string response = "response";
		}
		
		public const string ActionLogicalName = "msdyn_BulkAITestRun";
		
		public msdyn_BulkAITestRunResponse()
		{
		}
		
		public string response
		{
			get
			{
				if (this.Results.Contains("response"))
				{
					return ((string)(this.Results["response"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["response"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
