#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_TriggerIntegratedSearchAnalytics")]
	public partial class msdyn_TriggerIntegratedSearchAnalyticsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "msdyn_TriggerIntegratedSearchAnalytics";
		
		public msdyn_TriggerIntegratedSearchAnalyticsRequest()
		{
			this.RequestName = "msdyn_TriggerIntegratedSearchAnalytics";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_TriggerIntegratedSearchAnalytics")]
	public partial class msdyn_TriggerIntegratedSearchAnalyticsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string msdyn_IntegratedSearchAnalyticsResponse = "msdyn_IntegratedSearchAnalyticsResponse";
		}
		
		public const string ActionLogicalName = "msdyn_TriggerIntegratedSearchAnalytics";
		
		public msdyn_TriggerIntegratedSearchAnalyticsResponse()
		{
		}
		
		public string msdyn_IntegratedSearchAnalyticsResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_IntegratedSearchAnalyticsResponse"))
				{
					return ((string)(this.Results["msdyn_IntegratedSearchAnalyticsResponse"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["msdyn_IntegratedSearchAnalyticsResponse"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
