#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CloneAttachmentsPluginAction")]
	public partial class msdyn_CloneAttachmentsPluginActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SourceArticle = "SourceArticle";
			public const string ResultArticle = "ResultArticle";
		}
		
		public const string ActionLogicalName = "msdyn_CloneAttachmentsPluginAction";
		
		public string SourceArticle
		{
			get
			{
				if (this.Parameters.Contains("SourceArticle"))
				{
					return ((string)(this.Parameters["SourceArticle"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SourceArticle"] = value;
			}
		}
		
		public string ResultArticle
		{
			get
			{
				if (this.Parameters.Contains("ResultArticle"))
				{
					return ((string)(this.Parameters["ResultArticle"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResultArticle"] = value;
			}
		}
		
		public msdyn_CloneAttachmentsPluginActionRequest()
		{
			this.RequestName = "msdyn_CloneAttachmentsPluginAction";
			this.SourceArticle = default(string);
			this.ResultArticle = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CloneAttachmentsPluginAction")]
	public partial class msdyn_CloneAttachmentsPluginActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "msdyn_CloneAttachmentsPluginAction";
		
		public msdyn_CloneAttachmentsPluginActionResponse()
		{
		}
	}
}
#pragma warning restore CS1591
