#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SaveCalendar")]
	public partial class msdyn_SaveCalendarRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CalendarEventInfo = "CalendarEventInfo";
		}
		
		public const string ActionLogicalName = "msdyn_SaveCalendar";
		
		public string CalendarEventInfo
		{
			get
			{
				if (this.Parameters.Contains("CalendarEventInfo"))
				{
					return ((string)(this.Parameters["CalendarEventInfo"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CalendarEventInfo"] = value;
			}
		}
		
		public msdyn_SaveCalendarRequest()
		{
			this.RequestName = "msdyn_SaveCalendar";
			this.CalendarEventInfo = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SaveCalendar")]
	public partial class msdyn_SaveCalendarResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string InnerCalendarIds = "InnerCalendarIds";
		}
		
		public const string ActionLogicalName = "msdyn_SaveCalendar";
		
		public msdyn_SaveCalendarResponse()
		{
		}
		
		public string InnerCalendarIds
		{
			get
			{
				if (this.Results.Contains("InnerCalendarIds"))
				{
					return ((string)(this.Results["InnerCalendarIds"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["InnerCalendarIds"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
