#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DownloadMobileAppBuild")]
	public partial class msdyn_DownloadMobileAppBuildRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string BuildId = "BuildId";
			public const string msdyn_MobileApp = "msdyn_MobileApp";
		}
		
		public const string ActionLogicalName = "msdyn_DownloadMobileAppBuild";
		
		public string BuildId
		{
			get
			{
				if (this.Parameters.Contains("BuildId"))
				{
					return ((string)(this.Parameters["BuildId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BuildId"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference msdyn_MobileApp
		{
			get
			{
				if (this.Parameters.Contains("msdyn_MobileApp"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["msdyn_MobileApp"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["msdyn_MobileApp"] = value;
			}
		}
		
		public msdyn_DownloadMobileAppBuildRequest()
		{
			this.RequestName = "msdyn_DownloadMobileAppBuild";
			this.msdyn_MobileApp = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DownloadMobileAppBuild")]
	public partial class msdyn_DownloadMobileAppBuildResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "msdyn_DownloadMobileAppBuild";
		
		public msdyn_DownloadMobileAppBuildResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
