#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_create_virtual_table_v2")]
	public partial class msdyn_create_virtual_table_v2Request : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string use_environment_variable_for_dataset = "use_environment_variable_for_dataset";
			public const string virtual_table_external_name = "virtual_table_external_name";
			public const string primary_key_name = "primary_key_name";
			public const string virtual_table_schema_name = "virtual_table_schema_name";
			public const string solution_id = "solution_id";
			public const string environment_id = "environment_id";
			public const string virtual_table_columns = "virtual_table_columns";
			public const string virtual_table_plural_name = "virtual_table_plural_name";
			public const string dataset_value = "dataset_value";
			public const string primary_field_name = "primary_field_name";
			public const string connectionreference_display_name = "connectionreference_display_name";
			public const string connectionreference_logical_name = "connectionreference_logical_name";
			public const string connection_id = "connection_id";
			public const string virtual_table_name = "virtual_table_name";
			public const string connectionreference_id = "connectionreference_id";
			public const string environment_variable_names = "environment_variable_names";
			public const string datasource_name = "datasource_name";
			public const string datasource_id = "datasource_id";
		}
		
		public const string ActionLogicalName = "msdyn_create_virtual_table_v2";
		
		public bool use_environment_variable_for_dataset
		{
			get
			{
				if (this.Parameters.Contains("use_environment_variable_for_dataset"))
				{
					return ((bool)(this.Parameters["use_environment_variable_for_dataset"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["use_environment_variable_for_dataset"] = value;
			}
		}
		
		public string virtual_table_external_name
		{
			get
			{
				if (this.Parameters.Contains("virtual_table_external_name"))
				{
					return ((string)(this.Parameters["virtual_table_external_name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["virtual_table_external_name"] = value;
			}
		}
		
		public string primary_key_name
		{
			get
			{
				if (this.Parameters.Contains("primary_key_name"))
				{
					return ((string)(this.Parameters["primary_key_name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["primary_key_name"] = value;
			}
		}
		
		public string virtual_table_schema_name
		{
			get
			{
				if (this.Parameters.Contains("virtual_table_schema_name"))
				{
					return ((string)(this.Parameters["virtual_table_schema_name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["virtual_table_schema_name"] = value;
			}
		}
		
		public string solution_id
		{
			get
			{
				if (this.Parameters.Contains("solution_id"))
				{
					return ((string)(this.Parameters["solution_id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["solution_id"] = value;
			}
		}
		
		public string environment_id
		{
			get
			{
				if (this.Parameters.Contains("environment_id"))
				{
					return ((string)(this.Parameters["environment_id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["environment_id"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection virtual_table_columns
		{
			get
			{
				if (this.Parameters.Contains("virtual_table_columns"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["virtual_table_columns"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["virtual_table_columns"] = value;
			}
		}
		
		public string virtual_table_plural_name
		{
			get
			{
				if (this.Parameters.Contains("virtual_table_plural_name"))
				{
					return ((string)(this.Parameters["virtual_table_plural_name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["virtual_table_plural_name"] = value;
			}
		}
		
		public string dataset_value
		{
			get
			{
				if (this.Parameters.Contains("dataset_value"))
				{
					return ((string)(this.Parameters["dataset_value"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["dataset_value"] = value;
			}
		}
		
		public string primary_field_name
		{
			get
			{
				if (this.Parameters.Contains("primary_field_name"))
				{
					return ((string)(this.Parameters["primary_field_name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["primary_field_name"] = value;
			}
		}
		
		public string connectionreference_display_name
		{
			get
			{
				if (this.Parameters.Contains("connectionreference_display_name"))
				{
					return ((string)(this.Parameters["connectionreference_display_name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["connectionreference_display_name"] = value;
			}
		}
		
		public string connectionreference_logical_name
		{
			get
			{
				if (this.Parameters.Contains("connectionreference_logical_name"))
				{
					return ((string)(this.Parameters["connectionreference_logical_name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["connectionreference_logical_name"] = value;
			}
		}
		
		public string connection_id
		{
			get
			{
				if (this.Parameters.Contains("connection_id"))
				{
					return ((string)(this.Parameters["connection_id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["connection_id"] = value;
			}
		}
		
		public string virtual_table_name
		{
			get
			{
				if (this.Parameters.Contains("virtual_table_name"))
				{
					return ((string)(this.Parameters["virtual_table_name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["virtual_table_name"] = value;
			}
		}
		
		public string connectionreference_id
		{
			get
			{
				if (this.Parameters.Contains("connectionreference_id"))
				{
					return ((string)(this.Parameters["connectionreference_id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["connectionreference_id"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection environment_variable_names
		{
			get
			{
				if (this.Parameters.Contains("environment_variable_names"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["environment_variable_names"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["environment_variable_names"] = value;
			}
		}
		
		public string datasource_name
		{
			get
			{
				if (this.Parameters.Contains("datasource_name"))
				{
					return ((string)(this.Parameters["datasource_name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["datasource_name"] = value;
			}
		}
		
		public string datasource_id
		{
			get
			{
				if (this.Parameters.Contains("datasource_id"))
				{
					return ((string)(this.Parameters["datasource_id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["datasource_id"] = value;
			}
		}
		
		public msdyn_create_virtual_table_v2Request()
		{
			this.RequestName = "msdyn_create_virtual_table_v2";
			this.virtual_table_external_name = default(string);
			this.primary_key_name = default(string);
			this.dataset_value = default(string);
			this.primary_field_name = default(string);
			this.connection_id = default(string);
			this.virtual_table_name = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_create_virtual_table_v2")]
	public partial class msdyn_create_virtual_table_v2Response : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string virtual_table_id = "virtual_table_id";
		}
		
		public const string ActionLogicalName = "msdyn_create_virtual_table_v2";
		
		public msdyn_create_virtual_table_v2Response()
		{
		}
		
		public string virtual_table_id
		{
			get
			{
				if (this.Results.Contains("virtual_table_id"))
				{
					return ((string)(this.Results["virtual_table_id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["virtual_table_id"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
