#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_TriggerIntegratedSearchProvisioningApi")]
	public partial class msdyn_TriggerIntegratedSearchProvisioningApiRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string msdyn_DegreeOfParallelism = "msdyn_DegreeOfParallelism";
		}
		
		public const string ActionLogicalName = "msdyn_TriggerIntegratedSearchProvisioningApi";
		
		public string msdyn_DegreeOfParallelism
		{
			get
			{
				if (this.Parameters.Contains("msdyn_DegreeOfParallelism"))
				{
					return ((string)(this.Parameters["msdyn_DegreeOfParallelism"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_DegreeOfParallelism"] = value;
			}
		}
		
		public msdyn_TriggerIntegratedSearchProvisioningApiRequest()
		{
			this.RequestName = "msdyn_TriggerIntegratedSearchProvisioningApi";
			this.msdyn_DegreeOfParallelism = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_TriggerIntegratedSearchProvisioningApi")]
	public partial class msdyn_TriggerIntegratedSearchProvisioningApiResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string msdyn_TriggerProvisioningResponse = "msdyn_TriggerProvisioningResponse";
		}
		
		public const string ActionLogicalName = "msdyn_TriggerIntegratedSearchProvisioningApi";
		
		public msdyn_TriggerIntegratedSearchProvisioningApiResponse()
		{
		}
		
		public string msdyn_TriggerProvisioningResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_TriggerProvisioningResponse"))
				{
					return ((string)(this.Results["msdyn_TriggerProvisioningResponse"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["msdyn_TriggerProvisioningResponse"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
