#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SiteMapDiagnosis")]
	public partial class msdyn_SiteMapDiagnosisRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string IssueType = "IssueType";
			public const string ComponentInstance = "ComponentInstance";
		}
		
		public const string ActionLogicalName = "msdyn_SiteMapDiagnosis";
		
		public string IssueType
		{
			get
			{
				if (this.Parameters.Contains("IssueType"))
				{
					return ((string)(this.Parameters["IssueType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IssueType"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference ComponentInstance
		{
			get
			{
				if (this.Parameters.Contains("ComponentInstance"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["ComponentInstance"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["ComponentInstance"] = value;
			}
		}
		
		public msdyn_SiteMapDiagnosisRequest()
		{
			this.RequestName = "msdyn_SiteMapDiagnosis";
			this.IssueType = default(string);
			this.ComponentInstance = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SiteMapDiagnosis")]
	public partial class msdyn_SiteMapDiagnosisResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string HelpLink = "HelpLink";
			public const string Message = "Message";
			public const string RepairIssueType = "RepairIssueType";
			public const string ResultEntities = "ResultEntities";
			public const string ReturnStatus = "ReturnStatus";
		}
		
		public const string ActionLogicalName = "msdyn_SiteMapDiagnosis";
		
		public msdyn_SiteMapDiagnosisResponse()
		{
		}
		
		public string HelpLink
		{
			get
			{
				if (this.Results.Contains("HelpLink"))
				{
					return ((string)(this.Results["HelpLink"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["HelpLink"] = value;
			}
		}
		
		public string Message
		{
			get
			{
				if (this.Results.Contains("Message"))
				{
					return ((string)(this.Results["Message"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Message"] = value;
			}
		}
		
		public string RepairIssueType
		{
			get
			{
				if (this.Results.Contains("RepairIssueType"))
				{
					return ((string)(this.Results["RepairIssueType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["RepairIssueType"] = value;
			}
		}
		
		public string ResultEntities
		{
			get
			{
				if (this.Results.Contains("ResultEntities"))
				{
					return ((string)(this.Results["ResultEntities"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ResultEntities"] = value;
			}
		}
		
		public int ReturnStatus
		{
			get
			{
				if (this.Results.Contains("ReturnStatus"))
				{
					return ((int)(this.Results["ReturnStatus"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ReturnStatus"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
