#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msft_DataEngineIndexMgmt_GetIndexInfo")]
	public partial class msft_DataEngineIndexMgmt_GetIndexInfoRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string GetIndexInfo_KeyColumnsJson = "GetIndexInfo_KeyColumnsJson";
			public const string GetIndexInfo_LogicalTableName = "GetIndexInfo_LogicalTableName";
		}
		
		public const string ActionLogicalName = "msft_DataEngineIndexMgmt_GetIndexInfo";
		
		public string GetIndexInfo_KeyColumnsJson
		{
			get
			{
				if (this.Parameters.Contains("GetIndexInfo_KeyColumnsJson"))
				{
					return ((string)(this.Parameters["GetIndexInfo_KeyColumnsJson"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["GetIndexInfo_KeyColumnsJson"] = value;
			}
		}
		
		public string GetIndexInfo_LogicalTableName
		{
			get
			{
				if (this.Parameters.Contains("GetIndexInfo_LogicalTableName"))
				{
					return ((string)(this.Parameters["GetIndexInfo_LogicalTableName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["GetIndexInfo_LogicalTableName"] = value;
			}
		}
		
		public msft_DataEngineIndexMgmt_GetIndexInfoRequest()
		{
			this.RequestName = "msft_DataEngineIndexMgmt_GetIndexInfo";
			this.GetIndexInfo_KeyColumnsJson = default(string);
			this.GetIndexInfo_LogicalTableName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msft_DataEngineIndexMgmt_GetIndexInfo")]
	public partial class msft_DataEngineIndexMgmt_GetIndexInfoResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ExistsInMetaData = "ExistsInMetaData";
			public const string ExistsInSqlDB = "ExistsInSqlDB";
			public const string IsQueuedForAdhocIndexing = "IsQueuedForAdhocIndexing";
		}
		
		public const string ActionLogicalName = "msft_DataEngineIndexMgmt_GetIndexInfo";
		
		public msft_DataEngineIndexMgmt_GetIndexInfoResponse()
		{
		}
		
		public bool ExistsInMetaData
		{
			get
			{
				if (this.Results.Contains("ExistsInMetaData"))
				{
					return ((bool)(this.Results["ExistsInMetaData"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["ExistsInMetaData"] = value;
			}
		}
		
		public bool ExistsInSqlDB
		{
			get
			{
				if (this.Results.Contains("ExistsInSqlDB"))
				{
					return ((bool)(this.Results["ExistsInSqlDB"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["ExistsInSqlDB"] = value;
			}
		}
		
		public bool IsQueuedForAdhocIndexing
		{
			get
			{
				if (this.Results.Contains("IsQueuedForAdhocIndexing"))
				{
					return ((bool)(this.Results["IsQueuedForAdhocIndexing"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsQueuedForAdhocIndexing"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
