#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msft_DataEngineIndexMgmt_CreateIndex")]
	public partial class msft_DataEngineIndexMgmt_CreateIndexRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CreateIndex_QueueAdhocRequest = "CreateIndex_QueueAdhocRequest";
			public const string CreateIndex_KeyColumnsJson = "CreateIndex_KeyColumnsJson";
			public const string CreateIndex_LogicalTableName = "CreateIndex_LogicalTableName";
		}
		
		public const string ActionLogicalName = "msft_DataEngineIndexMgmt_CreateIndex";
		
		public bool CreateIndex_QueueAdhocRequest
		{
			get
			{
				if (this.Parameters.Contains("CreateIndex_QueueAdhocRequest"))
				{
					return ((bool)(this.Parameters["CreateIndex_QueueAdhocRequest"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["CreateIndex_QueueAdhocRequest"] = value;
			}
		}
		
		public string CreateIndex_KeyColumnsJson
		{
			get
			{
				if (this.Parameters.Contains("CreateIndex_KeyColumnsJson"))
				{
					return ((string)(this.Parameters["CreateIndex_KeyColumnsJson"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CreateIndex_KeyColumnsJson"] = value;
			}
		}
		
		public string CreateIndex_LogicalTableName
		{
			get
			{
				if (this.Parameters.Contains("CreateIndex_LogicalTableName"))
				{
					return ((string)(this.Parameters["CreateIndex_LogicalTableName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CreateIndex_LogicalTableName"] = value;
			}
		}
		
		public msft_DataEngineIndexMgmt_CreateIndexRequest()
		{
			this.RequestName = "msft_DataEngineIndexMgmt_CreateIndex";
			this.CreateIndex_QueueAdhocRequest = default(bool);
			this.CreateIndex_KeyColumnsJson = default(string);
			this.CreateIndex_LogicalTableName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msft_DataEngineIndexMgmt_CreateIndex")]
	public partial class msft_DataEngineIndexMgmt_CreateIndexResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CreateIndex_CreateResult = "CreateIndex_CreateResult";
		}
		
		public const string ActionLogicalName = "msft_DataEngineIndexMgmt_CreateIndex";
		
		public msft_DataEngineIndexMgmt_CreateIndexResponse()
		{
		}
		
		public bool CreateIndex_CreateResult
		{
			get
			{
				if (this.Results.Contains("CreateIndex_CreateResult"))
				{
					return ((bool)(this.Results["CreateIndex_CreateResult"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["CreateIndex_CreateResult"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
