#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("OnBackgroundOperationComplete")]
	public partial class OnBackgroundOperationCompleteRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CallbackUrl = "CallbackUrl";
			public const string LocationUrl = "LocationUrl";
			public const string BackgroundOperationId = "BackgroundOperationId";
			public const string PayloadType = "PayloadType";
		}
		
		public const string ActionLogicalName = "OnBackgroundOperationComplete";
		
		public string CallbackUrl
		{
			get
			{
				if (this.Parameters.Contains("CallbackUrl"))
				{
					return ((string)(this.Parameters["CallbackUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CallbackUrl"] = value;
			}
		}
		
		public string LocationUrl
		{
			get
			{
				if (this.Parameters.Contains("LocationUrl"))
				{
					return ((string)(this.Parameters["LocationUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LocationUrl"] = value;
			}
		}
		
		public System.Guid BackgroundOperationId
		{
			get
			{
				if (this.Parameters.Contains("BackgroundOperationId"))
				{
					return ((System.Guid)(this.Parameters["BackgroundOperationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["BackgroundOperationId"] = value;
			}
		}
		
		public int PayloadType
		{
			get
			{
				if (this.Parameters.Contains("PayloadType"))
				{
					return ((int)(this.Parameters["PayloadType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["PayloadType"] = value;
			}
		}
		
		public OnBackgroundOperationCompleteRequest()
		{
			this.RequestName = "OnBackgroundOperationComplete";
			this.LocationUrl = default(string);
			this.BackgroundOperationId = default(System.Guid);
			this.PayloadType = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("OnBackgroundOperationComplete")]
	public partial class OnBackgroundOperationCompleteResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string BackgroundOperationStateCode = "BackgroundOperationStateCode";
			public const string BackgroundOperationStatusCode = "BackgroundOperationStatusCode";
			public const string OperationName = "OperationName";
		}
		
		public const string ActionLogicalName = "OnBackgroundOperationComplete";
		
		public OnBackgroundOperationCompleteResponse()
		{
		}
		
		public int BackgroundOperationStateCode
		{
			get
			{
				if (this.Results.Contains("BackgroundOperationStateCode"))
				{
					return ((int)(this.Results["BackgroundOperationStateCode"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["BackgroundOperationStateCode"] = value;
			}
		}
		
		public int BackgroundOperationStatusCode
		{
			get
			{
				if (this.Results.Contains("BackgroundOperationStatusCode"))
				{
					return ((int)(this.Results["BackgroundOperationStatusCode"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["BackgroundOperationStatusCode"] = value;
			}
		}
		
		public string OperationName
		{
			get
			{
				if (this.Results.Contains("OperationName"))
				{
					return ((string)(this.Results["OperationName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["OperationName"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
