#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("PowerAutomateProxy")]
	public partial class PowerAutomateProxyRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string HttpMethod = "HttpMethod";
			public const string RelativeUrl = "RelativeUrl";
			public const string RequestHeaders = "RequestHeaders";
			public const string RequestBody = "RequestBody";
		}
		
		public const string ActionLogicalName = "PowerAutomateProxy";
		
		public string HttpMethod
		{
			get
			{
				if (this.Parameters.Contains("HttpMethod"))
				{
					return ((string)(this.Parameters["HttpMethod"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["HttpMethod"] = value;
			}
		}
		
		public string RelativeUrl
		{
			get
			{
				if (this.Parameters.Contains("RelativeUrl"))
				{
					return ((string)(this.Parameters["RelativeUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RelativeUrl"] = value;
			}
		}
		
		public string RequestHeaders
		{
			get
			{
				if (this.Parameters.Contains("RequestHeaders"))
				{
					return ((string)(this.Parameters["RequestHeaders"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RequestHeaders"] = value;
			}
		}
		
		public string RequestBody
		{
			get
			{
				if (this.Parameters.Contains("RequestBody"))
				{
					return ((string)(this.Parameters["RequestBody"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RequestBody"] = value;
			}
		}
		
		public PowerAutomateProxyRequest()
		{
			this.RequestName = "PowerAutomateProxy";
			this.HttpMethod = default(string);
			this.RelativeUrl = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("PowerAutomateProxy")]
	public partial class PowerAutomateProxyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string HttpStatusCode = "HttpStatusCode";
			public const string ResponseBody = "ResponseBody";
			public const string ResponseHeaders = "ResponseHeaders";
		}
		
		public const string ActionLogicalName = "PowerAutomateProxy";
		
		public PowerAutomateProxyResponse()
		{
		}
		
		public int HttpStatusCode
		{
			get
			{
				if (this.Results.Contains("HttpStatusCode"))
				{
					return ((int)(this.Results["HttpStatusCode"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["HttpStatusCode"] = value;
			}
		}
		
		public string ResponseBody
		{
			get
			{
				if (this.Results.Contains("ResponseBody"))
				{
					return ((string)(this.Results["ResponseBody"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ResponseBody"] = value;
			}
		}
		
		public string ResponseHeaders
		{
			get
			{
				if (this.Results.Contains("ResponseHeaders"))
				{
					return ((string)(this.Results["ResponseHeaders"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ResponseHeaders"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
