#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("PublishAllXmlAsync")]
	public partial class PublishAllXmlAsyncRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "PublishAllXmlAsync";
		
		public PublishAllXmlAsyncRequest()
		{
			this.RequestName = "PublishAllXmlAsync";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("PublishAllXmlAsync")]
	public partial class PublishAllXmlAsyncResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AsyncOperationId = "AsyncOperationId";
		}
		
		public const string ActionLogicalName = "PublishAllXmlAsync";
		
		public PublishAllXmlAsyncResponse()
		{
		}
		
		public System.Guid AsyncOperationId
		{
			get
			{
				if (this.Results.Contains("AsyncOperationId"))
				{
					return ((System.Guid)(this.Results["AsyncOperationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["AsyncOperationId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
