#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("PvaGetUserBots")]
	public partial class PvaGetUserBotsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RoleType = "RoleType";
		}
		
		public const string ActionLogicalName = "PvaGetUserBots";
		
		public int RoleType
		{
			get
			{
				if (this.Parameters.Contains("RoleType"))
				{
					return ((int)(this.Parameters["RoleType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["RoleType"] = value;
			}
		}
		
		public PvaGetUserBotsRequest()
		{
			this.RequestName = "PvaGetUserBots";
			this.RoleType = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("PvaGetUserBots")]
	public partial class PvaGetUserBotsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Bots = "Bots";
		}
		
		public const string ActionLogicalName = "PvaGetUserBots";
		
		public PvaGetUserBotsResponse()
		{
		}
		
		public string Bots
		{
			get
			{
				if (this.Results.Contains("Bots"))
				{
					return ((string)(this.Results["Bots"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Bots"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
