#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("querystructureddatastream")]
	public partial class querystructureddatastreamRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string maxRows = "maxRows";
			public const string additionalProperties = "additionalProperties";
			public const string options = "options";
			public const string queryText = "queryText";
			public const string skill = "skill";
		}
		
		public const string ActionLogicalName = "querystructureddatastream";
		
		public int maxRows
		{
			get
			{
				if (this.Parameters.Contains("maxRows"))
				{
					return ((int)(this.Parameters["maxRows"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["maxRows"] = value;
			}
		}
		
		public string additionalProperties
		{
			get
			{
				if (this.Parameters.Contains("additionalProperties"))
				{
					return ((string)(this.Parameters["additionalProperties"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["additionalProperties"] = value;
			}
		}
		
		public string[] options
		{
			get
			{
				if (this.Parameters.Contains("options"))
				{
					return ((string[])(this.Parameters["options"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["options"] = value;
			}
		}
		
		public string queryText
		{
			get
			{
				if (this.Parameters.Contains("queryText"))
				{
					return ((string)(this.Parameters["queryText"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["queryText"] = value;
			}
		}
		
		public string skill
		{
			get
			{
				if (this.Parameters.Contains("skill"))
				{
					return ((string)(this.Parameters["skill"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["skill"] = value;
			}
		}
		
		public querystructureddatastreamRequest()
		{
			this.RequestName = "querystructureddatastream";
			this.queryText = default(string);
			this.skill = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("querystructureddatastream")]
	public partial class querystructureddatastreamResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string response = "response";
		}
		
		public const string ActionLogicalName = "querystructureddatastream";
		
		public querystructureddatastreamResponse()
		{
		}
		
		public string response
		{
			get
			{
				if (this.Results.Contains("response"))
				{
					return ((string)(this.Results["response"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["response"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
