#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("QuestionAnalytics")]
	public partial class QuestionAnalyticsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string botId = "botId";
			public const string page = "page";
			public const string endDateTime = "endDateTime";
			public const string state = "state";
			public const string count = "count";
			public const string startDateTime = "startDateTime";
		}
		
		public const string ActionLogicalName = "QuestionAnalytics";
		
		public string botId
		{
			get
			{
				if (this.Parameters.Contains("botId"))
				{
					return ((string)(this.Parameters["botId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["botId"] = value;
			}
		}
		
		public int page
		{
			get
			{
				if (this.Parameters.Contains("page"))
				{
					return ((int)(this.Parameters["page"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["page"] = value;
			}
		}
		
		public string endDateTime
		{
			get
			{
				if (this.Parameters.Contains("endDateTime"))
				{
					return ((string)(this.Parameters["endDateTime"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["endDateTime"] = value;
			}
		}
		
		public string state
		{
			get
			{
				if (this.Parameters.Contains("state"))
				{
					return ((string)(this.Parameters["state"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["state"] = value;
			}
		}
		
		public int count
		{
			get
			{
				if (this.Parameters.Contains("count"))
				{
					return ((int)(this.Parameters["count"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["count"] = value;
			}
		}
		
		public string startDateTime
		{
			get
			{
				if (this.Parameters.Contains("startDateTime"))
				{
					return ((string)(this.Parameters["startDateTime"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["startDateTime"] = value;
			}
		}
		
		public QuestionAnalyticsRequest()
		{
			this.RequestName = "QuestionAnalytics";
			this.botId = default(string);
			this.endDateTime = default(string);
			this.state = default(string);
			this.startDateTime = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("QuestionAnalytics")]
	public partial class QuestionAnalyticsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string moreRecords = "moreRecords";
			public const string page = "page";
			public const string pagingCookie = "pagingCookie";
			public const string value = "value";
		}
		
		public const string ActionLogicalName = "QuestionAnalytics";
		
		public QuestionAnalyticsResponse()
		{
		}
		
		public bool moreRecords
		{
			get
			{
				if (this.Results.Contains("moreRecords"))
				{
					return ((bool)(this.Results["moreRecords"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["moreRecords"] = value;
			}
		}
		
		public int page
		{
			get
			{
				if (this.Results.Contains("page"))
				{
					return ((int)(this.Results["page"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["page"] = value;
			}
		}
		
		public string pagingCookie
		{
			get
			{
				if (this.Results.Contains("pagingCookie"))
				{
					return ((string)(this.Results["pagingCookie"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["pagingCookie"] = value;
			}
		}
		
		public string value
		{
			get
			{
				if (this.Results.Contains("value"))
				{
					return ((string)(this.Results["value"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["value"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
