#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RegisterFlowMachine")]
	public partial class RegisterFlowMachineRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string machineName = "machineName";
			public const string machineDescription = "machineDescription";
			public const string machineCapacity = "machineCapacity";
			public const string agentVersion = "agentVersion";
			public const string groupPublicKey = "groupPublicKey";
			public const string hostingType = "hostingType";
			public const string targetGroup = "targetGroup";
			public const string pictureInPictureSupport = "pictureInPictureSupport";
			public const string machineDomain = "machineDomain";
		}
		
		public const string ActionLogicalName = "RegisterFlowMachine";
		
		public string machineName
		{
			get
			{
				if (this.Parameters.Contains("machineName"))
				{
					return ((string)(this.Parameters["machineName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["machineName"] = value;
			}
		}
		
		public string machineDescription
		{
			get
			{
				if (this.Parameters.Contains("machineDescription"))
				{
					return ((string)(this.Parameters["machineDescription"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["machineDescription"] = value;
			}
		}
		
		public int machineCapacity
		{
			get
			{
				if (this.Parameters.Contains("machineCapacity"))
				{
					return ((int)(this.Parameters["machineCapacity"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["machineCapacity"] = value;
			}
		}
		
		public string agentVersion
		{
			get
			{
				if (this.Parameters.Contains("agentVersion"))
				{
					return ((string)(this.Parameters["agentVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["agentVersion"] = value;
			}
		}
		
		public string groupPublicKey
		{
			get
			{
				if (this.Parameters.Contains("groupPublicKey"))
				{
					return ((string)(this.Parameters["groupPublicKey"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["groupPublicKey"] = value;
			}
		}
		
		public int hostingType
		{
			get
			{
				if (this.Parameters.Contains("hostingType"))
				{
					return ((int)(this.Parameters["hostingType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["hostingType"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference targetGroup
		{
			get
			{
				if (this.Parameters.Contains("targetGroup"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["targetGroup"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["targetGroup"] = value;
			}
		}
		
		public int pictureInPictureSupport
		{
			get
			{
				if (this.Parameters.Contains("pictureInPictureSupport"))
				{
					return ((int)(this.Parameters["pictureInPictureSupport"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["pictureInPictureSupport"] = value;
			}
		}
		
		public string machineDomain
		{
			get
			{
				if (this.Parameters.Contains("machineDomain"))
				{
					return ((string)(this.Parameters["machineDomain"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["machineDomain"] = value;
			}
		}
		
		public RegisterFlowMachineRequest()
		{
			this.RequestName = "RegisterFlowMachine";
			this.machineName = default(string);
			this.machineCapacity = default(int);
			this.agentVersion = default(string);
			this.groupPublicKey = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RegisterFlowMachine")]
	public partial class RegisterFlowMachineResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string groupId = "groupId";
			public const string machineId = "machineId";
			public const string relayListenKeys = "relayListenKeys";
		}
		
		public const string ActionLogicalName = "RegisterFlowMachine";
		
		public RegisterFlowMachineResponse()
		{
		}
		
		public string groupId
		{
			get
			{
				if (this.Results.Contains("groupId"))
				{
					return ((string)(this.Results["groupId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["groupId"] = value;
			}
		}
		
		public string machineId
		{
			get
			{
				if (this.Results.Contains("machineId"))
				{
					return ((string)(this.Results["machineId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["machineId"] = value;
			}
		}
		
		public string relayListenKeys
		{
			get
			{
				if (this.Results.Contains("relayListenKeys"))
				{
					return ((string)(this.Results["relayListenKeys"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["relayListenKeys"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
