#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ReplicateCreate")]
	public partial class ReplicateCreateRequest<T> : Microsoft.Xrm.Sdk.OrganizationRequest
		where T : Microsoft.Xrm.Sdk.Entity, new ()
	{
		
		public static class Fields
		{
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "ReplicateCreate";
		
		public ReplicateCreateRequest() : 
				this(new T())
		{
		}
		
		public ReplicateCreateRequest(T target)
		{
			this.Target = target;
			this.RequestName = "ReplicateCreate";
		}
		
		public T Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((T)(this.Parameters["Target"]));
				}
				else
				{
					return default(T);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ReplicateCreate")]
	public partial class ReplicateCreateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string id = "id";
		}
		
		public const string ActionLogicalName = "ReplicateCreate";
		
		public ReplicateCreateResponse()
		{
		}
		
		public System.Guid id
		{
			get
			{
				if (this.Results.Contains("id"))
				{
					return ((System.Guid)(this.Results["id"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["id"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
