#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrieveBoolFeatureControlSetting")]
	public partial class RetrieveBoolFeatureControlSettingRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string FeatureControlName = "FeatureControlName";
			public const string NamespaceValue = "NamespaceValue";
		}
		
		public const string ActionLogicalName = "RetrieveBoolFeatureControlSetting";
		
		public string FeatureControlName
		{
			get
			{
				if (this.Parameters.Contains("FeatureControlName"))
				{
					return ((string)(this.Parameters["FeatureControlName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FeatureControlName"] = value;
			}
		}
		
		public string NamespaceValue
		{
			get
			{
				if (this.Parameters.Contains("NamespaceValue"))
				{
					return ((string)(this.Parameters["NamespaceValue"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["NamespaceValue"] = value;
			}
		}
		
		public RetrieveBoolFeatureControlSettingRequest()
		{
			this.RequestName = "RetrieveBoolFeatureControlSetting";
			this.FeatureControlName = default(string);
			this.NamespaceValue = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveBoolFeatureControlSetting")]
	public partial class RetrieveBoolFeatureControlSettingResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsEnabled = "IsEnabled";
		}
		
		public const string ActionLogicalName = "RetrieveBoolFeatureControlSetting";
		
		public RetrieveBoolFeatureControlSettingResponse()
		{
		}
		
		public bool IsEnabled
		{
			get
			{
				if (this.Results.Contains("IsEnabled"))
				{
					return ((bool)(this.Results["IsEnabled"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsEnabled"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
