#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrievePowerAppsConnectorApis")]
	public partial class RetrievePowerAppsConnectorApisRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "RetrievePowerAppsConnectorApis";
		
		public RetrievePowerAppsConnectorApisRequest()
		{
			this.RequestName = "RetrievePowerAppsConnectorApis";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrievePowerAppsConnectorApis")]
	public partial class RetrievePowerAppsConnectorApisResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string PowerAppsConnectorApis = "PowerAppsConnectorApis";
		}
		
		public const string ActionLogicalName = "RetrievePowerAppsConnectorApis";
		
		public RetrievePowerAppsConnectorApisResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection PowerAppsConnectorApis
		{
			get
			{
				if (this.Results.Contains("PowerAppsConnectorApis"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["PowerAppsConnectorApis"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["PowerAppsConnectorApis"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
