#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrieveMissingDependenciesWithMetadata")]
	public partial class RetrieveMissingDependenciesWithMetadataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SkipManagedDependencies = "SkipManagedDependencies";
			public const string SolutionUniqueName = "SolutionUniqueName";
		}
		
		public const string ActionLogicalName = "RetrieveMissingDependenciesWithMetadata";
		
		public bool SkipManagedDependencies
		{
			get
			{
				if (this.Parameters.Contains("SkipManagedDependencies"))
				{
					return ((bool)(this.Parameters["SkipManagedDependencies"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["SkipManagedDependencies"] = value;
			}
		}
		
		public string SolutionUniqueName
		{
			get
			{
				if (this.Parameters.Contains("SolutionUniqueName"))
				{
					return ((string)(this.Parameters["SolutionUniqueName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionUniqueName"] = value;
			}
		}
		
		public RetrieveMissingDependenciesWithMetadataRequest()
		{
			this.RequestName = "RetrieveMissingDependenciesWithMetadata";
			this.SkipManagedDependencies = default(bool);
			this.SolutionUniqueName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveMissingDependenciesWithMetadata")]
	public partial class RetrieveMissingDependenciesWithMetadataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string DependencyMetadataCollection = "DependencyMetadataCollection";
		}
		
		public const string ActionLogicalName = "RetrieveMissingDependenciesWithMetadata";
		
		public RetrieveMissingDependenciesWithMetadataResponse()
		{
		}
		
		public Microsoft.Crm.Sdk.Messages.DependencyMetadataCollection DependencyMetadataCollection
		{
			get
			{
				if (this.Results.Contains("DependencyMetadataCollection"))
				{
					return ((Microsoft.Crm.Sdk.Messages.DependencyMetadataCollection)(this.Results["DependencyMetadataCollection"]));
				}
				else
				{
					return default(Microsoft.Crm.Sdk.Messages.DependencyMetadataCollection);
				}
			}
			set
			{
				this.Results["DependencyMetadataCollection"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
