#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrievePowerAppsConnections")]
	public partial class RetrievePowerAppsConnectionsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "RetrievePowerAppsConnections";
		
		public RetrievePowerAppsConnectionsRequest()
		{
			this.RequestName = "RetrievePowerAppsConnections";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrievePowerAppsConnections")]
	public partial class RetrievePowerAppsConnectionsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string PowerAppsConnections = "PowerAppsConnections";
		}
		
		public const string ActionLogicalName = "RetrievePowerAppsConnections";
		
		public RetrievePowerAppsConnectionsResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection PowerAppsConnections
		{
			get
			{
				if (this.Results.Contains("PowerAppsConnections"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["PowerAppsConnections"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["PowerAppsConnections"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
