#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrieveMaskedAttributesForEntity")]
	public partial class RetrieveMaskedAttributesForEntityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntityLogicalName = "EntityLogicalName";
		}
		
		public const string ActionLogicalName = "RetrieveMaskedAttributesForEntity";
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public RetrieveMaskedAttributesForEntityRequest()
		{
			this.RequestName = "RetrieveMaskedAttributesForEntity";
			this.EntityLogicalName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveMaskedAttributesForEntity")]
	public partial class RetrieveMaskedAttributesForEntityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AttributeLogicalNames = "AttributeLogicalNames";
		}
		
		public const string ActionLogicalName = "RetrieveMaskedAttributesForEntity";
		
		public RetrieveMaskedAttributesForEntityResponse()
		{
		}
		
		public string[] AttributeLogicalNames
		{
			get
			{
				if (this.Results.Contains("AttributeLogicalNames"))
				{
					return ((string[])(this.Results["AttributeLogicalNames"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Results["AttributeLogicalNames"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
