#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrieveConnectorSettings")]
	public partial class RetrieveConnectorSettingsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "RetrieveConnectorSettings";
		
		public RetrieveConnectorSettingsRequest()
		{
			this.RequestName = "RetrieveConnectorSettings";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveConnectorSettings")]
	public partial class RetrieveConnectorSettingsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ConnectorSettings = "ConnectorSettings";
		}
		
		public const string ActionLogicalName = "RetrieveConnectorSettings";
		
		public RetrieveConnectorSettingsResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection ConnectorSettings
		{
			get
			{
				if (this.Results.Contains("ConnectorSettings"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["ConnectorSettings"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["ConnectorSettings"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
