#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrieveAppsWithDelegatedAccessPermissions")]
	public partial class RetrieveAppsWithDelegatedAccessPermissionsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string cloud = "cloud";
		}
		
		public const string ActionLogicalName = "RetrieveAppsWithDelegatedAccessPermissions";
		
		public Microsoft.Xrm.Sdk.OptionSetValue cloud
		{
			get
			{
				if (this.Parameters.Contains("cloud"))
				{
					return ((Microsoft.Xrm.Sdk.OptionSetValue)(this.Parameters["cloud"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.OptionSetValue);
				}
			}
			set
			{
				this.Parameters["cloud"] = value;
			}
		}
		
		public RetrieveAppsWithDelegatedAccessPermissionsRequest()
		{
			this.RequestName = "RetrieveAppsWithDelegatedAccessPermissions";
			this.cloud = default(Microsoft.Xrm.Sdk.OptionSetValue);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveAppsWithDelegatedAccessPermissions")]
	public partial class RetrieveAppsWithDelegatedAccessPermissionsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string result = "result";
		}
		
		public const string ActionLogicalName = "RetrieveAppsWithDelegatedAccessPermissions";
		
		public RetrieveAppsWithDelegatedAccessPermissionsResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection result
		{
			get
			{
				if (this.Results.Contains("result"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["result"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
