#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RunDataProcessingModule")]
	public partial class RunDataProcessingModuleRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string DataProcessingConfigurationId = "DataProcessingConfigurationId";
			public const string EndPoints = "EndPoints";
			public const string CallbackUri = "CallbackUri";
			public const string JobArguments = "JobArguments";
			public const string UpstreamResults = "UpstreamResults";
			public const string ScalarInputs = "ScalarInputs";
		}
		
		public const string ActionLogicalName = "RunDataProcessingModule";
		
		public string DataProcessingConfigurationId
		{
			get
			{
				if (this.Parameters.Contains("DataProcessingConfigurationId"))
				{
					return ((string)(this.Parameters["DataProcessingConfigurationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DataProcessingConfigurationId"] = value;
			}
		}
		
		public string[] EndPoints
		{
			get
			{
				if (this.Parameters.Contains("EndPoints"))
				{
					return ((string[])(this.Parameters["EndPoints"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["EndPoints"] = value;
			}
		}
		
		public string CallbackUri
		{
			get
			{
				if (this.Parameters.Contains("CallbackUri"))
				{
					return ((string)(this.Parameters["CallbackUri"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CallbackUri"] = value;
			}
		}
		
		public string[] JobArguments
		{
			get
			{
				if (this.Parameters.Contains("JobArguments"))
				{
					return ((string[])(this.Parameters["JobArguments"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["JobArguments"] = value;
			}
		}
		
		public string[] UpstreamResults
		{
			get
			{
				if (this.Parameters.Contains("UpstreamResults"))
				{
					return ((string[])(this.Parameters["UpstreamResults"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["UpstreamResults"] = value;
			}
		}
		
		public string[] ScalarInputs
		{
			get
			{
				if (this.Parameters.Contains("ScalarInputs"))
				{
					return ((string[])(this.Parameters["ScalarInputs"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["ScalarInputs"] = value;
			}
		}
		
		public RunDataProcessingModuleRequest()
		{
			this.RequestName = "RunDataProcessingModule";
			this.DataProcessingConfigurationId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RunDataProcessingModule")]
	public partial class RunDataProcessingModuleResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string HttpResponseStatus = "HttpResponseStatus";
			public const string OutputEntities = "OutputEntities";
		}
		
		public const string ActionLogicalName = "RunDataProcessingModule";
		
		public RunDataProcessingModuleResponse()
		{
		}
		
		public int HttpResponseStatus
		{
			get
			{
				if (this.Results.Contains("HttpResponseStatus"))
				{
					return ((int)(this.Results["HttpResponseStatus"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["HttpResponseStatus"] = value;
			}
		}
		
		public string OutputEntities
		{
			get
			{
				if (this.Results.Contains("OutputEntities"))
				{
					return ((string)(this.Results["OutputEntities"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["OutputEntities"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
