#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("SnapshotDatasource")]
	public partial class SnapshotDatasourceRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SourceDatalakeFolderUniqueName = "SourceDatalakeFolderUniqueName";
		}
		
		public const string ActionLogicalName = "SnapshotDatasource";
		
		public string SourceDatalakeFolderUniqueName
		{
			get
			{
				if (this.Parameters.Contains("SourceDatalakeFolderUniqueName"))
				{
					return ((string)(this.Parameters["SourceDatalakeFolderUniqueName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SourceDatalakeFolderUniqueName"] = value;
			}
		}
		
		public SnapshotDatasourceRequest()
		{
			this.RequestName = "SnapshotDatasource";
			this.SourceDatalakeFolderUniqueName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("SnapshotDatasource")]
	public partial class SnapshotDatasourceResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string SnapshotReference = "SnapshotReference";
		}
		
		public const string ActionLogicalName = "SnapshotDatasource";
		
		public SnapshotDatasourceResponse()
		{
		}
		
		public string SnapshotReference
		{
			get
			{
				if (this.Results.Contains("SnapshotReference"))
				{
					return ((string)(this.Results["SnapshotReference"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["SnapshotReference"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
