#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("SubstituteForAttribute")]
	public partial class SubstituteForAttributeRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string AttributeContent = "AttributeContent";
			public const string AttributeName = "AttributeName";
			public const string SubStore = "SubStore";
		}
		
		public const string ActionLogicalName = "SubstituteForAttribute";
		
		public string AttributeContent
		{
			get
			{
				if (this.Parameters.Contains("AttributeContent"))
				{
					return ((string)(this.Parameters["AttributeContent"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AttributeContent"] = value;
			}
		}
		
		public string AttributeName
		{
			get
			{
				if (this.Parameters.Contains("AttributeName"))
				{
					return ((string)(this.Parameters["AttributeName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AttributeName"] = value;
			}
		}
		
		public string SubStore
		{
			get
			{
				if (this.Parameters.Contains("SubStore"))
				{
					return ((string)(this.Parameters["SubStore"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SubStore"] = value;
			}
		}
		
		public SubstituteForAttributeRequest()
		{
			this.RequestName = "SubstituteForAttribute";
			this.AttributeContent = default(string);
			this.AttributeName = default(string);
			this.SubStore = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("SubstituteForAttribute")]
	public partial class SubstituteForAttributeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "SubstituteForAttribute";
		
		public SubstituteForAttributeResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.SubstitutionResult Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((Microsoft.Xrm.Sdk.SubstitutionResult)(this.Results["Result"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.SubstitutionResult);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
