#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pg.LetsMeet.Dataverse.Context
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("SubstituteForComponent")]
	public partial class SubstituteForComponentRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SubStore = "SubStore";
			public const string Entity = "Entity";
		}
		
		public const string ActionLogicalName = "SubstituteForComponent";
		
		public string SubStore
		{
			get
			{
				if (this.Parameters.Contains("SubStore"))
				{
					return ((string)(this.Parameters["SubStore"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SubStore"] = value;
			}
		}
		
		public object Entity
		{
			get
			{
				if (this.Parameters.Contains("Entity"))
				{
					return ((object)(this.Parameters["Entity"]));
				}
				else
				{
					return default(object);
				}
			}
			set
			{
				this.Parameters["Entity"] = value;
			}
		}
		
		public SubstituteForComponentRequest()
		{
			this.RequestName = "SubstituteForComponent";
			this.SubStore = default(string);
			this.Entity = default(object);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("SubstituteForComponent")]
	public partial class SubstituteForComponentResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "SubstituteForComponent";
		
		public SubstituteForComponentResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.SubstitutionResult Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((Microsoft.Xrm.Sdk.SubstitutionResult)(this.Results["Result"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.SubstitutionResult);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
